Repository enkidevs/curriculum, pull requests merged in 2018-05, with the labels that each got.

#745 clean up exercise explanations
  sql/dql/basic-queries/sql-practice-select.md
  sql/dql/basic-selects/sql-practice-select-1.md
  sql/dql/basic-selects/sql-practice-select-2.md
  sql/dql/basic-selects/sql-practice-where-comparison.md
  sql/dql/joins/sql-practice-min-max-multiple-tables.md
  sql/dql/what-is-sql/sql-practice-what-is-sql.md
  sql/dql/write/sql-practice-delete.md
  sql/dql/write/sql-practice-insert.md
  sql/dql/write/sql-practice-update.md
Labels: review

#746 patch taking-precedence
  javascript/core/types/taking-precedence.md
Labels: review

#757 📚❗️Standards Definition: Python
  python/core/README.md
  python/functional-programming/README.md
Labels: Python, review

#759 Patch Quiz question Weak vs Strict Equality Operator
  javascript/core/types-ii/weak-vs-strict-equality-operator.md
Labels: review

#767 Python Standards Definition retrigger
  python/core/README.md
  python/functional-programming/README.md
Labels: review

#753 📚❗️Standards Definition: SQL
  sql/ddl/README.md
  sql/dql/README.md
Labels: SQL, review

#754 📚❗️Standards Definition: Security
  .archived/security/application-security/README.md
  security/securing-unix-the-osi-model/README.md
Labels: Security, review

#755 📚❗️Standards Definition: Computer Science
  .archived/comp-sci/design-patterns/README.md
  comp-sci/data-structures-and-algorithms/README.md
  comp-sci/networking/README.md
Labels: Comp. Sci., review

#756 📚❗️Standards Definition: Linux
  linux/jobs-and-processes-data-manipulation/README.md
  linux/networking-and-security/README.md
  linux/system-and-package-management/README.md
  linux/user-and-file-management/README.md
Labels: Linux, review

#758 📚❗️Standards Definition: JavaScript
  javascript/browser-apis/README.md
  javascript/core/README.md
  javascript/ecmascript-2015/README.md
  javascript/node/README.md
  javascript/npm/README.md
Labels: JavaScript, review

#773 python retriggering 1
  python/core/advanced-queues/a-thread-safe-queue.md
  python/core/advanced-queues/heap-priority-queue-in-python.md
  python/core/advanced-queues/prioritize-your-queue.md
  python/core/advanced-queues/queue-s-and-threads.md
  python/core/advanced-queues/special-queue-methods.md
  python/core/advanced-referencing/context-manager-types-with.md
  python/core/advanced-referencing/implementing-weak-references.md
  python/core/advanced-referencing/there-is-more-to-copying.md
  python/core/advanced-referencing/weakref-callbacks.md
  python/core/advanced-referencing/weakref-proxies.md
  python/core/basic-file-manipulation/how-to-open-a-file-object.md
  python/core/basic-file-manipulation/i-o-functions.md
  python/core/basic-file-manipulation/other-operations-on-files.md
  python/core/basic-file-manipulation/reading-from-files.md
  python/core/basic-file-manipulation/writing-files.md
  python/core/bits-bytes-hexadecimals/bytearray-objects.md
  python/core/bits-bytes-hexadecimals/bytes-type.md
  python/core/bits-bytes-hexadecimals/get-the-most-of-float-s.md
  python/core/bits-bytes-hexadecimals/get-the-most-of-int-s.md
  python/core/bits-bytes-hexadecimals/operations-with-bytes-and-bytearray.md
  python/core/classes-i/class-keywords.md
  python/core/classes-i/creating-classes.md
Labels: review

#774 python retriggering 2
  python/core/classes-i/method-overriding.md
  python/core/classes-i/py-practice-inheritance.md
  python/core/classes-i/py-practice-using-classes.md
  python/core/classes-i/python-inheritance.md
  python/core/classes-i/using-classes.md
  python/core/classes-ii/class-vs-instance-variables.md
  python/core/classes-ii/instance-objects.md
  python/core/classes-ii/method-objects.md
  python/core/classes-ii/private-variables.md
  python/core/classes-iii/custom-exceptions-as-classes.md
  python/core/classes-iii/dynamically-create-types.md
  python/core/classes-iii/metaclasses.md
  python/core/classes-iii/special-attributes-of-objects-and-classes.md
  python/core/console-and-operators/arithmetic-operators.md
  python/core/console-and-operators/execution-order-of-arithmetic-operators.md
  python/core/console-and-operators/indentation-and-commenting.md
  python/core/console-and-operators/more-complex-arithmetic-operators.md
  python/core/console-and-operators/printing-to-the-console.md
  python/core/console-and-operators/simple-way-of-swapping-variables.md
  python/core/control-structures/boolean-operators.md
  python/core/control-structures/chain-comparison-operators.md
  python/core/control-structures/if-statements.md
  python/core/control-structures/py-practice-control-structures.md
  python/core/control-structures/py-practice-flow-control-sudoku.md
  python/core/control-structures/py-practice-flow-control.md
  python/core/control-structures/the-in-operator.md
  python/core/control-structures/the-is-operator.md
  python/core/control-structures/the-not-operator.md
  python/core/deep-into-collections/best-way-to-implement-a-simple-queue.md
  python/core/deep-into-collections/double-ended-queues-with-deque.md
  python/core/deep-into-collections/enhance-your-tuple-s.md
  python/core/deep-into-collections/enum.md
  python/core/deep-into-collections/get-more-with-collections.md
  python/core/functions/calling-functions.md
  python/core/functions/defining-functions.md
  python/core/functions/nested-functions.md
  python/core/functions/py-function-arguments.md
  python/core/functions/py-more-practice-functions.md
  python/core/functions/py-practice-ciphers.md
  python/core/functions/py-practice-functions.md
Labels: review

#776 python retriggering 4
  python/core/more-on-lists/using-a-list-as-a-stack.md
  python/core/more-on-lists/using-lists-as-queues.md
  python/core/more-on-sets/complex-set-operations.md
  python/core/more-on-sets/immutable-sets-with-frozenset.md
  python/core/more-on-sets/mixing-sets-and-frozensets.md
  python/core/more-on-sets/set-operations.md
  python/core/playing-with-time/datetime-module.md
  python/core/playing-with-time/datetime-object.md
  python/core/playing-with-time/playing-with-time.md
  python/core/playing-with-time/time-object.md
  python/core/playing-with-time/timedelta-object.md
  python/core/recipes/a-simple-way-to-select-a-random-item-from-a-list-tuple-data-stucture.md
  python/core/recipes/combining-multiple-lists-item-by-item.md
  python/core/recipes/keep-large-lists-sorted-with-bisect.md
  python/core/recipes/parallel-sorting-of-lists.md
  python/core/string-recipes/format-text-paragraphs-with-textwrap.md
  python/core/string-recipes/recipe-to-normalize-text.md
  python/core/string-recipes/regular-expressions.md
  python/core/string-recipes/stringprep-module.md
  python/core/string-recipes/unicode-character-database-at-your-hands.md
  python/core/testing/doctests.md
  python/core/testing/mocking-tests.md
  python/core/testing/nose-testing.md
  python/core/testing/pytest.md
  python/core/testing/unit-testing.md
  python/core/utilities-i/check-available-python-modules.md
  python/core/utilities-i/how-to-count.md
  python/core/utilities-i/schedule-events-with-sched.md
  python/core/utilities-i/your-own-python-calendar.md
  python/core/utilities-ii/compare-sequences-with-difflib.md
  python/core/utilities-ii/coroutine-utility-function.md
  python/core/utilities-ii/get-the-similarity-ratio-of-two-sequences.md
  python/core/utilities-ii/use-struct-to-work-with-binary-data.md
  python/core/utilities-ii/working-with-junk-data.md
  python/core/working-with-strings/efficient-concatenation-with-join.md
  python/core/working-with-strings/pythonic-substring-testing.md
  python/core/working-with-strings/string-formatting.md
  python/core/working-with-strings/string-operations.md
  python/core/working-with-strings/three-ways-to-substitute-a-substring-of-a-string.md
Labels: review

#777 javascript retriggering 1
  javascript/core/array-methods/apply-map-function-to-array-items.md
  javascript/core/array-methods/filtering-items-out-of-an-array.md
  javascript/core/array-methods/get-a-random-item-from-an-array.md
  javascript/core/array-methods/how-to-merge-two-arrays.md
  javascript/core/array-methods/js-practice-array-concat.md
  javascript/core/array-methods/js-practice-array-every.md
  javascript/core/array-methods/js-practice-array-filter.md
  javascript/core/array-methods/js-practice-array-map.md
  javascript/core/array-methods/js-practice-array-reduce.md
  javascript/core/array-methods/js-practice-array-reverse.md
  javascript/core/array-methods/shuffle-an-array-using-sort-and-random.md
  javascript/core/arrays/arrays-can-be-used-as-stack.md
  javascript/core/arrays/arrays.md
  javascript/core/arrays/foo-features-and-fun-facts.md
  javascript/core/arrays/js-practice-array-isarray.md
  javascript/core/arrays/js-practice-array-push.md
  javascript/core/arrays/js-practice-array-splice.md
  javascript/core/arrays/js-practice-arrays.md
  javascript/core/arrays/setting-the-length-of-an-array.md
  javascript/core/arrays/splice.md
  javascript/core/async-tips/error-first-callbacks.md
  javascript/core/async-tips/inversion-of-control.md
  javascript/core/async-tips/name-your-callback-functions-to-avoid-callback-hell.md
  javascript/core/async-tips/transform-values-into-promises.md
  javascript/core/async-tips/using-timers-with-extra-arguments.md
  javascript/core/async/async-a-history.md
  javascript/core/async/csp-using-async-csp-and-es7.md
  javascript/core/async/csp-using-js-csp.md
  javascript/core/async/flow-control-using-co.md
  javascript/core/async/js-practice-async.md
  javascript/core/async/js-practice-event-loop.md
  javascript/core/async/the-difference-between-parallel-asynchronous-and-concurrent.md
  javascript/core/errors/catch-is-block-scoped.md
  javascript/core/errors/debugging.md
  javascript/core/errors/detect-an-error-type.md
  javascript/core/errors/exceptions.md
  javascript/core/errors/js-practice-custom-errors.md
  javascript/core/errors/js-practice-error-throwing.md
  javascript/core/errors/js-practice-invalid-input.md
  javascript/core/flow-control/data-type-comparison-in-switch-statements.md
  javascript/core/flow-control/if-statement.md
  javascript/core/flow-control/js-practice-for-loops.md
  javascript/core/flow-control/js-practice-if-else.md
  javascript/core/flow-control/js-practice-switch-case.md
  javascript/core/flow-control/js-practice-while-loops.md
  javascript/core/flow-control/loops-part-1.md
  javascript/core/flow-control/loops-part-2.md
  javascript/core/functions-i/access-a-function-s-arguments-as-an-array.md
  javascript/core/functions-i/declaring-functions.md
  javascript/core/functions-i/function-arguments.md
  javascript/core/functions-i/function-constructor-vs-function-expression.md
  javascript/core/functions-i/functions-can-be-declared-after-use.md
  javascript/core/functions-i/js-practice-bind.md
  javascript/core/functions-i/js-practice-call.md
  javascript/core/functions-i/js-practice-closures.md
  javascript/core/functions-i/js-practice-default-parameters.md
  javascript/core/functions-i/js-practice-sort-i.md
  javascript/core/functions-i/js-practice-sort-ii.md
Labels: review

#780 javascript retrigger 4
  javascript/node/patterns/middleware-pipeline-design-pattern.md
  javascript/node/patterns/process-nexttick-callback-pattern.md
  javascript/node/patterns/use-conventional-property-names-for-error-handling-in-node-js.md
  javascript/node/processes-clustering/clustering.md
  javascript/node/processes-clustering/manage-child-processes-in-node.md
  javascript/node/processes-clustering/master-and-worker-process-communication.md
  javascript/node/processes-clustering/master-processes-and-worker-processes.md
  javascript/node/processes-clustering/the-worker-class.md
  javascript/node/quirks/avoid-command-injection.md
  javascript/node/quirks/node-and-sudo.md
  javascript/node/quirks/node-os-module.md
  javascript/node/streams/chaining-readable-streams.md
  javascript/node/streams/piping-readable-streams.md
  javascript/node/streams/readable-streams.md
  javascript/node/streams/what-are-streams.md
  javascript/node/streams/writable-streams.md
  javascript/node/tools/automatic-compilation-for-node-with-nodemon.md
  javascript/node/tools/bulk-write-in-node-with-cork.md
  javascript/node/tools/how-to-debug-node-js.md
  javascript/node/tools/the-built-in-node-debugger.md
  javascript/node/web-servers/basic-web-server-with-express.md
  javascript/node/web-servers/custom-node-repl-server.md
  javascript/node/web-servers/http-server-in-node.md
  javascript/node/web-servers/the-http-module-for-servers.md
  javascript/npm/features-i/available-binaries-for-scripting.md
  javascript/npm/features-i/npm-scripting.md
  javascript/npm/features-i/npm-variables.md
  javascript/npm/features-i/remote-scripts.md
  javascript/npm/features-i/scripts-lifecycle.md
  javascript/npm/features-ii/abbreviate-commands-in-npm.md
  javascript/npm/features-ii/environmental-variables-and-flags-for-npm.md
  javascript/npm/features-ii/npm-verifies-sha1-hashes-of-packages.md
  javascript/npm/features-ii/optionaldependencies-in-npm.md
  javascript/npm/intro-npm/package-json.md
  javascript/npm/intro-npm/semantic-versioning.md
  javascript/npm/intro-npm/setting-up-npm.md
  javascript/npm/intro-npm/what-is-npm.md
  javascript/npm/intro-npm/why-use-npm.md
  javascript/npm/packages-modules/dependencies.md
  javascript/npm/packages-modules/deprecated-peer-dependencies.md
  javascript/npm/packages-modules/how-npm3-handles-dependencies.md
  javascript/npm/packages-modules/packages-vs-modules.md
  javascript/npm/packages-modules/private-packages.md
  javascript/npm/publishing/check-data-about-a-package.md
  javascript/npm/publishing/creating-a-node-module.md
  javascript/npm/publishing/how-to-publish-your-own-packages.md
  javascript/npm/publishing/package-distribution-tags.md
  javascript/npm/publishing/prepare-your-module-for-publishing.md
  javascript/npm/publishing/registry-user-accounts-for-npm.md
  javascript/npm/publishing/tests.md
  javascript/npm/tools-i/bump-package-version-in-npm.md
  javascript/npm/tools-i/deprecate-npm-packages.md
  javascript/npm/tools-i/lock-down-dependency-versions-by-shrinkwrapping.md
  javascript/npm/tools-i/manage-local-node-modules-with-npm-link.md
  javascript/npm/tools-i/manipulate-npm-packages-cache.md
Labels: review

#790 add new objective to web
  web/html/README.md
Labels: review

#724 [Python PQ/RQ] Queues
  python/core/advanced-queues/heap-priority-queue-in-python.md
  python/core/advanced-queues/prioritize-your-queue.md
Labels: Python, review

#714 [Python PQ/RQ] Utilities
  python/core/testing/doctests.md
  python/core/utilities-i/schedule-events-with-sched.md
Labels: Python, review

#747 Fix: create an `empty arrays of size 3` in Javascript
  comp-sci/data-structures-and-algorithms/intro-data-structures/the-array-data-structure.md
Labels: review

#748 Fix: typo in Python datetime course
  python/core/playing-with-time/datetime-object.md
Labels: review

#791 slice 1 of web topic refactor
  web/html/README.md
  web/html/core-html-elements/README.md
  web/html/core-html-elements/headings-h1-h6.md
  web/html/core-html-elements/paragraphs.md
  web/html/core-html-elements/update-hyperlinks.md
  web/html/core-html-elements/update-images.md
  web/html/forms-ii/README.md
  web/html/forms-ii/check-boxes.md
  web/html/forms-ii/checkbox-groups.md
  web/html/forms-ii/dropdown-list.md
  web/html/forms-ii/html-select.md
  web/html/forms-ii/intro-list.md
  web/html/forms-ii/radio-buttons.md
  web/html/forms/README.md
  web/html/forms/input-element.md
  web/html/forms/intro-form.md
  web/html/forms/submit-and-reset.md
  web/html/forms/text-area.md
  web/html/forms/text-field.md
  web/html/html-structure/README.md
  web/html/html-structure/attributes.md
  web/html/html-structure/comments.md
  web/html/html-structure/elements.md
  web/html/html-structure/html-structure-define.md
  web/html/html-structure/html-tags.md
  web/html/images/README.md
  web/html/images/image-alt.md
  web/html/images/image-base.md
  web/html/images/image-height-width.md
  web/html/images/image-map.md
  web/html/images/image-title.md
  web/html/images/image-types.md
  web/html/media/README.md
  web/html/media/audio.md
  web/html/media/embed.md
  web/html/media/video.md
  web/html/web-page-structure/README.md
  web/html/web-page-structure/doctype.md
  web/html/web-page-structure/head-element.md
  web/html/web-page-structure/html-element.md
  web/html/web-page-structure/optional-elements.md
Labels: review

#794 smaller slice of part 2
  web/html/README.md
  web/html/meta-elements/README.md
  web/html/meta-elements/author.md
  web/html/meta-elements/charset.md
  web/html/meta-elements/description.md
  web/html/meta-elements/http-equiv.md
  web/html/meta-elements/keywords.md
  web/html/meta-elements/meta-intro.md
  web/html/meta-elements/robots.md
  web/html/sectioning-elements/README.md
  web/html/sectioning-elements/div.md
  web/html/sectioning-elements/footer.md
  web/html/sectioning-elements/header.md
  web/html/sectioning-elements/main.md
  web/html/sectioning-elements/nav.md
Labels: review

#795 smaller slice of part two
  web/html/README.md
  web/html/forms-iii/README.md
  web/html/forms-iii/intro-step.md
  web/html/forms-iii/min-and-max.md
  web/html/forms-iii/pattern-regexp.md
  web/html/forms-iii/placeholder.md
  web/html/forms-iii/range.md
  web/html/forms-iii/type-password.md
  web/html/forms-iv/README.md
  web/html/forms-iv/formaction.md
  web/html/forms-iv/formenctype.md
  web/html/forms-iv/formmethod.md
  web/html/forms-iv/formnovalidate-and-novalidate.md
  web/html/forms-iv/formtarget.md
  web/html/forms-iv/height-and-width.md
  web/html/forms-iv/image-button.md
  web/html/forms-v/README.md
  web/html/forms-v/autocomplete.md
  web/html/forms-v/autofocus.md
  web/html/forms-v/multiple.md
  web/html/forms-v/oninput.md
  web/html/forms-v/output.md
Labels: review

#796 Smaller slice of part three
  web/styling/README.md
  web/styling/box-model/README.md
  web/styling/box-model/borders.md
  web/styling/box-model/margin-and-padding.md
  web/styling/box-model/the-box-model.md
  web/styling/box-model/the-box-sizing-property.md
  web/styling/box-model/the-display-property.md
  web/styling/css-basics/README.md
  web/styling/css-basics/applying-css.md
  web/styling/css-basics/common-css-properties-values.md
  web/styling/css-basics/css-specificity.md
  web/styling/css-basics/internal-css.md
  web/styling/css-basics/relative-css-properties.md
  web/styling/css-basics/will-this-work-on-ie8.md
  web/styling/dimensioning-and-box-sizing/README.md
  web/styling/dimensioning-and-box-sizing/inherit-box-sizing.md
  web/styling/dimensioning-and-box-sizing/use-box-sizing-to-define-an-element-s-width-and-height-properties.md
  web/styling/dimensioning-and-box-sizing/use-em-instead-of-px-for-sizes.md
  web/styling/dimensioning-and-box-sizing/vertical-percentages-are-relative-to-container-width-not-height.md
  web/styling/dimensioning-and-box-sizing/vh-and-vw-vmin-and-vmax.md
  web/styling/intro-css/README.md
  web/styling/intro-css/basic-selectors.md
  web/styling/intro-css/class-and-id-selectors.md
  web/styling/intro-css/css-declaration.md
  web/styling/intro-css/what-is-cascading.md
  web/styling/intro-css/what-is-css.md
  web/styling/positioning/README.md
  web/styling/positioning/block-elements-characteristics.md
  web/styling/positioning/floating-elements.md
  web/styling/positioning/inline-block-elements-characteristics.md
  web/styling/positioning/inline-elements-characteristics.md
  web/styling/positioning/positioning-elements.md
  web/styling/practical-css/README.md
  web/styling/practical-css/add-line-height-to-body.md
  web/styling/practical-css/c-s-splat.md
  web/styling/practical-css/debug-with-the-selector.md
  web/styling/practical-css/difference-between-initial-and-inherit.md
  web/styling/practical-css/page-breaks-for-printing.md
  web/styling/practical-css/the-difference-between-display-none-and-visibility-hidden.md
Labels: review

#798 smaller slice of two
  web/html/README.md
  web/html/best-practices/README.md
  web/html/best-practices/alt-with-images.md
  web/html/best-practices/close-all-html-elements.md
  web/html/best-practices/conditional-comments-ie9.md
  web/html/best-practices/doctype-always-first.md
  web/html/best-practices/html-vs-htm.md
  web/html/best-practices/lowercase-element-names.md
  web/html/best-practices/quote-attribute-values.md
  web/html/citation-elements/README.md
  web/html/citation-elements/address.md
  web/html/citation-elements/blockquotes.md
  web/html/citation-elements/intro-bdi.md
  web/html/citation-elements/intro-bdo.md
  web/html/citation-elements/intro-cite.md
  web/html/citation-elements/intro-q.md
  web/html/computer-code/README.md
  web/html/computer-code/intro-code.md
  web/html/computer-code/intro-kbd.md
  web/html/computer-code/intro-pre.md
  web/html/computer-code/intro-samp.md
  web/html/computer-code/intro-var.md
  web/html/html-entities/README.md
  web/html/html-entities/ampersand.md
  web/html/html-entities/copyright.md
  web/html/html-entities/greater-and-less-than.md
  web/html/html-entities/non-breaking-space.md
  web/html/html-versions/README.md
  web/html/html-versions/html4-xhtml-and-html5.md
  web/html/semantic-sections/README.md
  web/html/semantic-sections/article.md
  web/html/semantic-sections/aside.md
  web/html/semantic-sections/figure-and-figcaption.md
  web/html/semantic-sections/section.md
  web/html/semantic-sections/semantic-containers.md
Labels: review

#799 few tweaks to exercises
  sql/ddl/alter/sql-practice-alter-table.md
  sql/ddl/alter/sql-practice-define-default-seq-3.md
Labels: review

#766 Web Topic Refactor
  .archived/web/fundamentals/html5-input-form-attributes/README.md
  web/html/README.md
  web/html/html-basics/divisions-and-spans.md
  web/html/html-basics/headings-and-paragraphs.md
  web/html/html-basics/hyperlinks.md
  web/html/html-basics/hypertext-markup-language.md
  web/html/html-basics/images.md
  web/styling/README.md
  web/styling/animations/README.md
  web/styling/animations/animation-basics-in-css.md
  web/styling/animations/chaining-animations.md
  web/styling/animations/prepare-for-will-change.md
  web/styling/animations/shorthand-transitions.md
  web/styling/animations/using-animation-delay-in-debugging.md
  web/styling/features/README.md
  web/styling/features/at-rules.md
  web/styling/features/calc-for-simpler-maths.md
  web/styling/features/combining-selectors.md
  web/styling/features/use-svg-for-icons.md
  web/styling/features/use-z-index-to-specify-the-stack-order-of-elements-that-overlap.md
  web/styling/flexbox/README.md
  web/styling/flexbox/avoid-margin-hacks-with-flexbox.md
  web/styling/flexbox/flexbox-flex-wrap.md
  web/styling/flexbox/flexbox-justify-content.md
  web/styling/flexbox/flexbox-order.md
  web/styling/flexbox/using-flex-grow.md
  web/styling/flexbox/using-flex-shrink.md
  web/styling/pseudo-classes-i/README.md
  web/styling/pseudo-classes-i/required-and-optional-pseudo-classes.md
  web/styling/pseudo-classes-i/the-hover-pseudo-class.md
  web/styling/pseudo-classes-i/the-nth-child-property.md
  web/styling/pseudo-classes-i/use-not-to-apply-unapply-styles.md
  web/styling/pseudo-classes-i/use-pseudo-classes-to-describe-a-special-state-of-an-element.md
  web/styling/pseudo-classes-ii/README.md
  web/styling/pseudo-classes-ii/drag-and-drop-pseudo-class-drop.md
  web/styling/pseudo-classes-ii/empty-and-blank.md
  web/styling/pseudo-classes-ii/highlight-input-forms-using-focus-pseudo-class.md
  web/styling/pseudo-classes-ii/in-range-and-out-of-range.md
  web/styling/pseudo-classes-ii/matches-any-pseudo-class-matches.md
  web/styling/pseudo-elements/README.md
  web/styling/pseudo-elements/change-selected-area-color.md
  web/styling/pseudo-elements/drop-caps-with-first-letter.md
  web/styling/pseudo-elements/styling-elements-using-before-and-after.md
  web/styling/pseudo-elements/use-attribute-selectors-with-empty-links.md
  web/styling/pseudo-elements/use-pseudo-elements-to-style-specific-parts-of-an-element.md
  web/styling/typography/README.md
  web/styling/typography/a-great-font-resource-google-font-api.md
  web/styling/typography/change-the-color-of-the-decoration-with-text-decoration-color.md
  web/styling/typography/change-the-style-of-the-decoration-with-text-decoration-style.md
  web/styling/typography/existential-crisis.md
  web/styling/typography/letter-spacing-property.md
  web/styling/typography/using-the-font-variant-property-to-transform-text-to-small-caps.md
Labels: review

#499 [Devops] [Docker] [WIP] Docker course
  devops/docker/bind-mounts.md
  devops/docker/container-philosophy.md
  devops/docker/containers.md
  devops/docker/docker-cli.md
  devops/docker/docker-dns.md
  devops/docker/docker-platform.md
  devops/docker/dockerfile.md
  devops/docker/image-registries.md
  devops/docker/image-tags.md
  devops/docker/images.md
  devops/docker/networks.md
  devops/docker/volumes.md
  devops/docker/what-is-docker.md
Labels: work in progress

#801 remove wrong insight reference
  web/html/html-entities/README.md
Labels: review

#804 fix wrong answer, add back ticks to answers
  web/html/html-entities/greater-and-less-than.md
Labels: review
