Repository enkidevs/curriculum, pull requests merged in 2018-03, with the labels that each got.

#569 sql: refractor ordering
  sql/README.md
  sql/ddl/README.md
  sql/ddl/alter/README.md
  sql/ddl/create/README.md
  sql/ddl/data-types/README.md
  sql/ddl/indices/README.md
  sql/ddl/storing-blobs/README.md
  sql/ddl/storing-json/README.md
  sql/dql/README.md
  sql/dql/aggregate-queries/README.md
  sql/dql/basic-queries/README.md
  sql/dql/database-clients/README.md
  sql/dql/joins/README.md
  sql/dql/what-is-sql/README.md
  sql/dql/write/README.md
Labels: review

#574 git: refractor ordering
  git/README.md
  git/essentials/README.md
  git/essentials/branching/README.md
  git/essentials/branching/fetching-a-remote-branch.md
  git/essentials/branching/managing-branches.md
  git/essentials/branching/pulling-a-remote-branch.md
  git/essentials/branching/pushing-to-a-remote-branch.md
  git/essentials/branching/setting-the-upstream-branch.md
  git/essentials/branching/what-is-rebasing.md
  git/essentials/commits/README.md
  git/essentials/features-i/README.md
  git/essentials/features-ii/README.md
  git/essentials/features-iii/README.md
  git/essentials/fundamentals/README.md
  git/essentials/getting-started/README.md
  git/essentials/local-repository/README.md
  git/essentials/remote-repository/README.md
  git/workflow/README.md
  git/workflow/branches/README.md
  git/workflow/finding-commits/README.md
  git/workflow/help/README.md
  git/workflow/logging/README.md
  git/workflow/merges/README.md
  git/workflow/staging-i/README.md
  git/workflow/staging-ii/README.md
  git/workflow/tips/README.md
  git/workflow/work-smart/README.md
  git/workflow/workflow/README.md
Labels: review

#567 comp-sci: refractor content ordering
  comp-sci/README.md
  comp-sci/data-structures-and-algorithms/README.md
  comp-sci/data-structures-and-algorithms/algorithms-i/README.md
  comp-sci/data-structures-and-algorithms/algorithms-ii/README.md
  comp-sci/data-structures-and-algorithms/binary-search-tree/README.md
  comp-sci/data-structures-and-algorithms/binary-search-tree/oh-that-was-the-answer.md
  comp-sci/data-structures-and-algorithms/graph-algorithms/README.md
  comp-sci/data-structures-and-algorithms/heap-and-trie/README.md
  comp-sci/data-structures-and-algorithms/intro-data-structures/README.md
  comp-sci/data-structures-and-algorithms/intro-graphs/README.md
  comp-sci/data-structures-and-algorithms/intro-graphs/what-should-it-be-stored-in.md
  comp-sci/data-structures-and-algorithms/mst-algorithms/README.md
  comp-sci/data-structures-and-algorithms/tree-traversals/README.md
  comp-sci/networking/README.md
  comp-sci/networking/fundamentals-i/README.md
  comp-sci/networking/fundamentals-ii/README.md
  comp-sci/networking/http-status-codes/README.md
  comp-sci/networking/intro-to-http/README.md
  comp-sci/networking/metrics/README.md
  comp-sci/networking/requests-responses/README.md
  comp-sci/networking/tools/README.md
  comp-sci/networking/tools/networking-quiz.md
Labels: review

#575 web: refractor ordering
  web/README.md
  web/html-and-css-basics/README.md
  web/html-and-css-basics/animations/README.md
  web/html-and-css-basics/box-model/README.md
  web/html-and-css-basics/css-basics/README.md
  web/html-and-css-basics/dimensioning-and-box-sizing/README.md
  web/html-and-css-basics/features/README.md
  web/html-and-css-basics/flexbox/README.md
  web/html-and-css-basics/html-basics/README.md
  web/html-and-css-basics/intro-css/README.md
  web/html-and-css-basics/positioning/README.md
  web/html-and-css-basics/practical-css/README.md
  web/html-and-css-basics/pseudo-classes-i/README.md
  web/html-and-css-basics/pseudo-classes-ii/README.md
  web/html-and-css-basics/pseudo-elements/README.md
  web/html-and-css-basics/typography/README.md
  web/styling/README.md
  web/styling/centring-recipes/README.md
  web/styling/colors-tips/README.md
  web/styling/css-animation/README.md
  web/styling/css-animation/animations-in-webkit-browsers.md
  web/styling/css-animation/making-shapes-with-transform.md
  web/styling/css-animation/manipulating-shapes-using-css-border.md
  web/styling/css-animation/manipulating-shapes-using-css-clip-path.md
  web/styling/css-animation/manipulating-shapes-using-css-shape-outside.md
  web/styling/css-animation/pause-and-play-css-animations.md
  web/styling/positioning-tips/README.md
  web/styling/recipes/README.md
  web/styling/responsive-design-tips/README.md
  web/styling/sass-i/README.md
  web/styling/sass-ii/README.md
  web/styling/sass-iii/README.md
  web/styling/styling-i/README.md
  web/styling/styling-ii/README.md
  web/styling/styling-iii/README.md
Labels: review

#573 python: content refractoring
  python/README.md
  python/core/README.md
  python/core/advanced-referencing/README.md
  python/core/basic-file-manipulation/README.md
  python/core/classes-i/README.md
  python/core/classes-ii/README.md
  python/core/classes-iii/README.md
  python/core/console-and-operators/README.md
  python/core/control-structures/README.md
  python/core/functions/README.md
  python/core/fundamental-data-structures/README.md
  python/core/intro-to-modules/README.md
  python/core/is-your-python-healthy/README.md
  python/core/looping/README.md
  python/core/math-recipes/README.md
  python/core/math-recipes/generating-random-numbers.md
  python/core/math-recipes/math-for-complex-numbers.md
  python/core/math-recipes/python-s-fractions.md
  python/core/math-recipes/python-s-math.md
  python/core/math-recipes/working-with-decimals.md
  python/core/meet-python/README.md
  python/core/playing-with-time/README.md
  python/core/string-recipes/README.md
  python/core/string-recipes/format-text-paragraphs-with-textwrap.md
  python/core/string-recipes/recipe-to-normalize-text.md
  python/core/string-recipes/regular-expressions.md
  python/core/string-recipes/stringprep-module.md
  python/core/string-recipes/unicode-character-database-at-your-hands.md
  python/core/testing/README.md
  python/core/tips/README.md
  python/core/utilities-i/README.md
  python/core/utilities-ii/README.md
  python/data-structures/README.md
  python/data-structures/advanced-queues/README.md
  python/data-structures/bits-bytes-hexadecimals/README.md
  python/data-structures/deep-into-collections/README.md
  python/data-structures/memory-allocation/README.md
  python/data-structures/more-on-dictionaries/README.md
  python/data-structures/more-on-lists/README.md
  python/data-structures/more-on-sets/README.md
  python/data-structures/recipes/README.md
  python/data-structures/working-with-strings/README.md
  python/functional-programming/README.md
  python/functional-programming/arrays-i/README.md
  python/functional-programming/arrays-ii/README.md
  python/functional-programming/comprehension/README.md
  python/functional-programming/decorators/README.md
  python/functional-programming/functional-programming/README.md
  python/functional-programming/generators/README.md
  python/functional-programming/immutability/README.md
  python/functional-programming/iterators/README.md
Labels: review

#582 remove weird line causing errors in parser
  python/functional-programming/arrays-i/the-reversed-built-in-function.md
Labels: review

#572 Added onboarding form to curriculum readme
  README.md
Labels: review

#555 Git review
  git/essentials/features-iii/what-is-a-hook.md
  git/essentials/fundamentals/branches-in-git.md
  git/essentials/fundamentals/what-is-version-control.md
  git/essentials/local-repository/stashing.md
  git/workflow/help/getting-help.md
  git/workflow/tips/custom-colour-options.md
  git/workflow/work-smart/add-autocorrect-to-git.md
Labels: Git, awaiting review, good first issue, review

#553 Fixing bug where practice and revision were switched
  sql/dql/write/delete-clause.md
Labels: review

#584 Update Manifests to match new structure for soon-deprecated courses
  java/classes-objects/README.md
  java/data-types/README.md
  java/error-handling/README.md
  java/external-processes/README.md
  java/generics/README.md
  java/gui/README.md
  java/libraries/README.md
  java/multithreading/README.md
  java/patterns/README.md
  java/performance-tuning/README.md
  javascript/angular/README.md
  javascript/browserify/README.md
  javascript/classes/README.md
  javascript/express/README.md
  javascript/functions/README.md
  javascript/grunt/README.md
  javascript/gulp/README.md
  javascript/jasmine/README.md
  javascript/mocha-and-chai/README.md
  javascript/redux/README.md
  javascript/testing/README.md
  javascript/webpack/README.md
  linux/data-manipulation/README.md
  linux/file-management/README.md
  linux/networking/README.md
  linux/permissions-users/README.md
  linux/pipeline/README.md
  linux/security/README.md
  linux/terminals-shells/README.md
  python/generators/README.md
  python/iterators/README.md
  python/standard-library/README.md
  python/system-interaction/README.md
  web/animations/README.md
  web/css4/README.md
  web/drawing/README.md
  web/fundamentals/README.md
  web/positioning/README.md
Labels: review

#601 js-cluster workout manifest new structure
  javascript/cluster/README.md
Labels: review

#602 Structure: update leftover course manifests
  git/branching/README.md
  git/tools/README.md
  java/annotations/README.md
  java/threads-locks/README.md
  python/data-manipulation/README.md
Labels: review

#626 javascript/core : update leftover workouts manifests
  javascript/core/arrays-and-equality/README.md
  javascript/core/basics/README.md
  javascript/core/in-depth-i/README.md
  javascript/core/quirks-i/README.md
  javascript/core/quirks-ii/README.md
  javascript/core/tips-i/README.md
  javascript/core/tips-ii/README.md
  javascript/core/tips-iii/README.md
  javascript/core/using-the-double-tilde-game/README.md
Labels: review

#589 [JS] Datatypes Exercises
  javascript/core/types/README.md
  javascript/core/types/js-practice-arrays.md
  javascript/core/types/js-practice-booleans.md
  javascript/core/types/js-practice-numbers.md
  javascript/core/types/js-practice-objects.md
  javascript/core/types/js-practice-strings.md
Labels: review

#618 [JS] Error Handling Exercises
  javascript/core/errors/js-practice-custom-errors.md
  javascript/core/errors/js-practice-error-throwing.md
  javascript/core/errors/js-practice-invalid-input.md
Labels: review

#590 [JS] Flow Control Exercises
  javascript/core/flow-control/README.md
  javascript/core/flow-control/js-practice-for-loops.md
  javascript/core/flow-control/js-practice-if-else.md
  javascript/core/flow-control/js-practice-switch-case.md
  javascript/core/flow-control/js-practice-while-loops.md
Labels: review

#591 [JS] Functions Exercises
  javascript/core/functions-i/README.md
  javascript/core/functions-i/js-practice-closures.md
  javascript/core/functions-i/js-practice-default-parameters.md
  javascript/core/functions-i/js-practice-sort-i.md
  javascript/core/functions-i/js-practice-sort-ii.md
Labels: review

#611 [JS] Classes and Inheritance
  javascript/core/objects/README.md
  javascript/core/objects/js-practice-class-inheritance-i.md
  javascript/core/objects/js-practice-class-inheritance-ii.md
  javascript/core/objects/js-practice-classes-i.md
  javascript/core/objects/js-practice-classes-ii.md
  javascript/core/objects/js-practice-getters.md
  javascript/core/objects/js-practice-setters.md
Labels: review

#592 [JS] Standard Library Exercises
  javascript/core/recipes-i/README.md
  javascript/core/recipes-i/js-practice-array-concat.md
  javascript/core/recipes-i/js-practice-array-every.md
  javascript/core/recipes-i/js-practice-array-filter.md
  javascript/core/recipes-i/js-practice-array-isarray.md
  javascript/core/recipes-i/js-practice-array-map.md
  javascript/core/recipes-i/js-practice-array-push.md
  javascript/core/recipes-i/js-practice-array-reduce.md
  javascript/core/recipes-i/js-practice-array-reverse.md
  javascript/core/recipes-i/js-practice-array-splice.md
  javascript/core/recipes-i/js-practice-date.md
  javascript/core/recipes-i/js-practice-math-log.md
  javascript/core/recipes-i/js-practice-math-max.md
  javascript/core/recipes-i/js-practice-math-pow.md
  javascript/core/recipes-i/js-practice-math-random.md
  javascript/core/recipes-i/js-practice-math-round.md
  javascript/core/recipes-i/js-practice-number-tofixed.md
  javascript/core/recipes-i/js-practice-number-tostring.md
  javascript/core/recipes-i/js-practice-string-charat.md
  javascript/core/recipes-i/js-practice-string-concat.md
  javascript/core/recipes-i/js-practice-string-indexof.md
  javascript/core/recipes-i/js-practice-string-slice.md
  javascript/core/recipes-i/js-practice-string-touppercase.md
  javascript/core/recipes-i/js-practice-string-trim.md
Labels: review

#597 [JS] Async Exercises
  javascript/core/async/README.md
  javascript/core/async/js-practice-async-await.md
  javascript/core/async/js-practice-async.md
  javascript/core/async/js-practice-event-loop.md
  javascript/core/async/js-practice-promises.md
Labels: review

#605 [Python] Data structures exercises
  .gitignore
  python/data-structures/py-practice-data-structure.md
  python/data-structures/py-practice-iterator.md
  python/data-structures/py-practice-iterator2.md
  python/data-structures/py-practice-strings.md
Labels: review

#620 [Python] Data manipulation
  python/data-manipulation/py-practice-data-manipulation.md
  python/data-manipulation/py-practice-data-manipulation2.md
Labels: review

#617 [Python] Data manipulation with standard library
  python/standard-library/py-practice-binary-data.md
  python/standard-library/py-practice-encrypt.md
  python/standard-library/py-practice-math-modules.md
  python/standard-library/py-practice-string-manip.md
  python/standard-library/py-practice-string-manip2.md
  python/standard-library/py-practice-string-manip3.md
Labels: review

#616 [Python] Modules
  python/core/intro-to-modules/py-practice-modules.md
  python/core/intro-to-modules/py-practice-modules2.md
  python/core/intro-to-modules/py-practice-package-modules.md
  python/core/py-practice-package-modules2.md
Labels: review

#614 [Python] Object-Oriented exercises
  python/core/classes-i/py-practice-inheritance.md
  python/core/classes-i/py-practice-using-classes.md
Labels: review

#613 [Python] Standard library
  python/standard-library/py-practice-csv-files.md
  python/standard-library/py-practice-files.md
  python/standard-library/py-practice-standard-library.md
Labels: review

#610 [Python] Functions
  python/core/functions/py-more-practice-functions.md
  python/core/functions/py-practice-ciphers.md
  python/core/functions/py-practice-functions-scope.md
  python/core/functions/py-practice-functions.md
  python/core/functions/py-practice-functions2.md
Labels: review

#609 [Python] Flow control
  python/core/control-structures/py-practice-control-structures.md
  python/core/control-structures/py-practice-flow-control-sudoku.md
  python/core/control-structures/py-practice-flow-control.md
Labels: review

#600 [JS] Execution Context exercises
  javascript/core/functions-i/README.md
  javascript/core/functions-i/js-practice-bind.md
  javascript/core/functions-i/js-practice-call.md
  javascript/core/functions-i/js-practice-spreads.md
  javascript/core/functions-i/js-practice-this.md
Labels: review

#615 [Python] Developer environment
  python/core/meet-python/py-practice-py2-environment.md
Labels: review

#629 Python rerender
  python/core/classes-i/py-practice-inheritance.md
  python/core/classes-i/py-practice-using-classes.md
  python/core/control-structures/py-practice-control-structures.md
  python/core/control-structures/py-practice-flow-control-sudoku.md
  python/core/control-structures/py-practice-flow-control.md
  python/core/functions/py-more-practice-functions.md
  python/core/functions/py-practice-ciphers.md
  python/core/functions/py-practice-functions-scope.md
  python/core/functions/py-practice-functions.md
  python/core/functions/py-practice-functions2.md
  python/core/fundamental-data-structures/py-practice-boolean.md
  python/core/fundamental-data-structures/py-practice-enumartor.md
  python/core/fundamental-data-structures/py-practice-mapping.md
  python/core/fundamental-data-structures/py-practice-mapping2.md
  python/core/fundamental-data-structures/py-practice-sequence.md
  python/core/intro-to-modules/py-practice-modules.md
  python/core/intro-to-modules/py-practice-modules2.md
  python/core/intro-to-modules/py-practice-package-modules.md
  python/core/is-your-python-healthy/py-practice-control-statement.md
  python/core/is-your-python-healthy/py-practice-syntax.md
  python/core/looping/py-practice-iterable.md
  python/core/looping/py-practice-iterable2.md
  python/core/looping/py-practice-loops.md
  python/core/looping/py-practice-next-iter.md
  python/core/math-recipes/py-practice-encryption.md
  python/core/py-practice-package-modules2.md
  python/data-manipulation/py-practice-data-manipulation.md
  python/data-manipulation/py-practice-data-manipulation2.md
  python/data-structures/py-practice-data-structure.md
  python/data-structures/py-practice-iterator.md
  python/data-structures/py-practice-iterator2.md
  python/data-structures/py-practice-strings.md
  python/standard-library/py-practice-binary-data.md
  python/standard-library/py-practice-csv-files.md
  python/standard-library/py-practice-encrypt.md
  python/standard-library/py-practice-files.md
  python/standard-library/py-practice-math-modules.md
  python/standard-library/py-practice-standard-library.md
  python/standard-library/py-practice-string-manip.md
  python/standard-library/py-practice-string-manip2.md
  python/standard-library/py-practice-string-manip3.md
Labels: review

#640 remove metadata from Python/Data-Structures to prep for deprecation
  python/data-structures/README.md
Labels: review

#637 sql standards
  sql/ddl/alter/add-column.md
  sql/ddl/alter/add-constraint.md
  sql/ddl/alter/add-default-value.md
  sql/ddl/alter/add-rule.md
  sql/ddl/alter/add-trigger.md
  sql/ddl/create/create-a-database.md
  sql/ddl/create/create-a-table.md
  sql/ddl/indices/create-indexes.md
  sql/ddl/indices/when-to-add-indexes.md
  sql/dql/aggregate-queries/avg-clause.md
  sql/dql/aggregate-queries/count-clause.md
  sql/dql/aggregate-queries/distinct-clause.md
  sql/dql/aggregate-queries/group-by-clause.md
  sql/dql/aggregate-queries/min-and-max-clauses.md
  sql/dql/aggregate-queries/sum-clause.md
  sql/dql/basic-queries/order-by-clause.md
  sql/dql/basic-queries/select.md
  sql/dql/basic-queries/where-2.md
  sql/dql/basic-queries/where-3.md
  sql/dql/basic-queries/where.md
  sql/dql/database-clients/command-line-client.md
  sql/dql/database-clients/gui-client.md
  sql/dql/database-clients/java-database-packages.md
  sql/dql/database-clients/node-database-packages.md
  sql/dql/database-clients/python-database-packages.md
  sql/dql/database-clients/what-is-a-database-client.md
  sql/dql/joins/full-join.md
  sql/dql/joins/inner-join.md
  sql/dql/joins/left-and-right-joins.md
  sql/dql/joins/multiple-joins.md
  sql/dql/joins/union.md
  sql/dql/what-is-sql/connection-strings.md
  sql/dql/what-is-sql/database-server-types.md
  sql/dql/what-is-sql/what-is-a-database-server.md
  sql/dql/what-is-sql/what-is-an-rdbms.md
  sql/dql/what-is-sql/what-is-sql.md
  sql/dql/write/delete-clause.md
  sql/dql/write/insert.md
  sql/dql/write/update-clause.md
Labels: review

#631 Javascript Exercise Rerender
  javascript/core/async/js-practice-async-await.md
  javascript/core/async/js-practice-async.md
  javascript/core/async/js-practice-event-loop.md
  javascript/core/async/js-practice-promises.md
  javascript/core/errors/js-practice-custom-errors.md
  javascript/core/errors/js-practice-error-throwing.md
  javascript/core/errors/js-practice-invalid-input.md
  javascript/core/flow-control/js-practice-for-loops.md
  javascript/core/flow-control/js-practice-if-else.md
  javascript/core/flow-control/js-practice-switch-case.md
  javascript/core/flow-control/js-practice-while-loops.md
  javascript/core/functions-i/js-practice-bind.md
  javascript/core/functions-i/js-practice-call.md
  javascript/core/functions-i/js-practice-closures.md
  javascript/core/functions-i/js-practice-default-parameters.md
  javascript/core/functions-i/js-practice-sort-i.md
  javascript/core/functions-i/js-practice-sort-ii.md
  javascript/core/functions-i/js-practice-spreads.md
  javascript/core/functions-i/js-practice-this.md
  javascript/core/objects/js-practice-class-inheritance-i.md
  javascript/core/objects/js-practice-class-inheritance-ii.md
  javascript/core/objects/js-practice-classes-i.md
  javascript/core/objects/js-practice-classes-ii.md
  javascript/core/objects/js-practice-getters.md
  javascript/core/objects/js-practice-setters.md
  javascript/core/recipes-i/js-practice-array-concat.md
  javascript/core/recipes-i/js-practice-array-every.md
  javascript/core/recipes-i/js-practice-array-filter.md
  javascript/core/recipes-i/js-practice-array-isarray.md
  javascript/core/recipes-i/js-practice-array-map.md
  javascript/core/recipes-i/js-practice-array-push.md
  javascript/core/recipes-i/js-practice-array-reduce.md
  javascript/core/recipes-i/js-practice-array-reverse.md
  javascript/core/recipes-i/js-practice-array-splice.md
  javascript/core/recipes-i/js-practice-date.md
  javascript/core/recipes-i/js-practice-math-log.md
  javascript/core/recipes-i/js-practice-math-max.md
  javascript/core/recipes-i/js-practice-math-pow.md
  javascript/core/recipes-i/js-practice-math-random.md
  javascript/core/recipes-i/js-practice-math-round.md
  javascript/core/recipes-i/js-practice-number-tofixed.md
  javascript/core/recipes-i/js-practice-number-tostring.md
  javascript/core/recipes-i/js-practice-string-charat.md
  javascript/core/recipes-i/js-practice-string-concat.md
  javascript/core/recipes-i/js-practice-string-indexof.md
  javascript/core/recipes-i/js-practice-string-slice.md
  javascript/core/recipes-i/js-practice-string-touppercase.md
  javascript/core/recipes-i/js-practice-string-trim.md
  javascript/core/types/js-practice-arrays.md
  javascript/core/types/js-practice-booleans.md
  javascript/core/types/js-practice-numbers.md
  javascript/core/types/js-practice-objects.md
  javascript/core/types/js-practice-strings.md
Labels: review

#632 Python reordering
  python/core/classes-i/py-practice-inheritance.md
  python/core/classes-i/py-practice-using-classes.md
  python/core/control-structures/py-practice-control-structures.md
  python/core/control-structures/py-practice-flow-control-sudoku.md
  python/core/control-structures/py-practice-flow-control.md
  python/core/functions/py-more-practice-functions.md
  python/core/functions/py-practice-ciphers.md
  python/core/functions/py-practice-functions-scope.md
  python/core/functions/py-practice-functions.md
  python/core/functions/py-practice-functions2.md
  python/core/fundamental-data-structures/py-practice-boolean.md
  python/core/fundamental-data-structures/py-practice-enumartor.md
  python/core/fundamental-data-structures/py-practice-mapping.md
  python/core/fundamental-data-structures/py-practice-mapping2.md
  python/core/fundamental-data-structures/py-practice-sequence.md
  python/core/intro-to-modules/py-practice-modules.md
  python/core/intro-to-modules/py-practice-modules2.md
  python/core/intro-to-modules/py-practice-package-modules.md
  python/core/is-your-python-healthy/py-practice-control-statement.md
  python/core/is-your-python-healthy/py-practice-syntax.md
  python/core/looping/py-practice-iterable.md
  python/core/looping/py-practice-iterable2.md
  python/core/looping/py-practice-loops.md
  python/core/looping/py-practice-next-iter.md
  python/core/math-recipes/py-practice-encryption.md
  python/core/py-practice-package-modules2.md
  python/data-manipulation/py-practice-data-manipulation.md
  python/data-manipulation/py-practice-data-manipulation2.md
  python/data-structures/py-practice-data-structure.md
  python/data-structures/py-practice-iterator.md
  python/data-structures/py-practice-iterator2.md
  python/data-structures/py-practice-strings.md
  python/standard-library/py-practice-binary-data.md
  python/standard-library/py-practice-csv-files.md
  python/standard-library/py-practice-encrypt.md
  python/standard-library/py-practice-files.md
  python/standard-library/py-practice-math-modules.md
  python/standard-library/py-practice-standard-library.md
  python/standard-library/py-practice-string-manip.md
  python/standard-library/py-practice-string-manip2.md
  python/standard-library/py-practice-string-manip3.md
Labels: review

#643 Updated SQL table syntax
  sql/ddl/alter/add-column.md
  sql/ddl/alter/add-constraint.md
  sql/ddl/alter/add-default-value.md
  sql/ddl/alter/add-rule.md
  sql/ddl/indices/create-indexes.md
  sql/ddl/indices/when-to-add-indexes.md
  sql/ddl/storing-json/storing-json-in-mssql.md
  sql/ddl/storing-json/storing-json-in-mysql.md
  sql/ddl/storing-json/storing-json-in-postgresql.md
  sql/dql/aggregate-queries/avg-clause.md
  sql/dql/aggregate-queries/count-clause.md
  sql/dql/aggregate-queries/distinct-clause.md
  sql/dql/aggregate-queries/group-by-clause.md
  sql/dql/aggregate-queries/min-and-max-clauses.md
  sql/dql/aggregate-queries/sum-clause.md
  sql/dql/basic-queries/order-by-clause.md
  sql/dql/basic-queries/select.md
  sql/dql/basic-queries/where-2.md
  sql/dql/basic-queries/where-3.md
  sql/dql/basic-queries/where.md
  sql/dql/joins/full-join.md
  sql/dql/joins/inner-join.md
  sql/dql/joins/left-and-right-joins.md
  sql/dql/joins/multiple-joins.md
  sql/dql/joins/union.md
  sql/dql/write/delete-clause.md
  sql/dql/write/update-clause.md
Labels: review

#645 Minor fix to sql table
  sql/dql/joins/multiple-joins.md
Labels: review

#653 Code language tag fix re trigger
  web/styling/sass-i/sass-supported-comments.md
Labels: review

#650 add objectives to sql
  sql/ddl/alter/add-column.md
  sql/ddl/alter/add-constraint.md
  sql/ddl/alter/add-default-value.md
  sql/ddl/alter/add-rule.md
  sql/ddl/alter/add-trigger.md
  sql/ddl/create/create-a-database.md
  sql/ddl/create/create-a-table.md
  sql/ddl/data-types/add-support-for-other-character-sets.md
  sql/ddl/data-types/encoding-and-collation.md
  sql/ddl/data-types/sql-numeric-data-types.md
  sql/ddl/data-types/sql-string-data-types.md
  sql/ddl/data-types/sql-text-data-type.md
  sql/ddl/indices/create-indexes.md
  sql/ddl/indices/when-to-add-indexes.md
  sql/ddl/storing-blobs/blobs-in-a-rdbms.md
  sql/ddl/storing-blobs/storing-blobs-in-mssql.md
  sql/ddl/storing-blobs/storing-blobs-in-mysql.md
  sql/ddl/storing-blobs/storing-blobs-in-psql.md
  sql/ddl/storing-json/storing-json-in-an-rdbms.md
  sql/ddl/storing-json/storing-json-in-mssql.md
  sql/ddl/storing-json/storing-json-in-mysql.md
  sql/ddl/storing-json/storing-json-in-postgresql.md
  sql/dql/aggregate-queries/avg-clause.md
  sql/dql/aggregate-queries/count-clause.md
  sql/dql/aggregate-queries/distinct-clause.md
  sql/dql/aggregate-queries/group-by-clause.md
  sql/dql/aggregate-queries/min-and-max-clauses.md
  sql/dql/aggregate-queries/sum-clause.md
  sql/dql/basic-queries/order-by-clause.md
  sql/dql/basic-queries/select.md
  sql/dql/basic-queries/where-2.md
  sql/dql/basic-queries/where-3.md
  sql/dql/basic-queries/where.md
  sql/dql/database-clients/command-line-client.md
  sql/dql/database-clients/gui-client.md
  sql/dql/database-clients/java-database-packages.md
  sql/dql/database-clients/node-database-packages.md
  sql/dql/database-clients/python-database-packages.md
  sql/dql/database-clients/what-is-a-database-client.md
  sql/dql/joins/full-join.md
  sql/dql/joins/inner-join.md
  sql/dql/joins/left-and-right-joins.md
  sql/dql/joins/multiple-joins.md
  sql/dql/joins/union.md
  sql/dql/what-is-sql/connection-strings.md
  sql/dql/what-is-sql/database-server-types.md
  sql/dql/write/delete-clause.md
  sql/dql/write/insert.md
  sql/dql/write/update-clause.md
Labels: SQL, ready to merge, review

#531 Blockchain c1w1
  blockchain/fundamentals/the-blockchain/README.md
  blockchain/fundamentals/the-blockchain/bc-practice-blockchain.md
  blockchain/fundamentals/the-blockchain/bc-practice-blocks.md
  blockchain/fundamentals/the-blockchain/blockchain-components.md
  blockchain/fundamentals/the-blockchain/blocks.md
  blockchain/fundamentals/the-blockchain/what-is-a-blockchain.md
Labels: Blockchain, review

#534 Blockchain c1w2
  blockchain/fundamentals/building-the-ledger/README.md
  blockchain/fundamentals/building-the-ledger/identity-and-consensus.md
  blockchain/fundamentals/building-the-ledger/malicious-nodes.md
  blockchain/fundamentals/building-the-ledger/the-ledger.md
  blockchain/fundamentals/building-the-ledger/verifying-the-ledger.md
  blockchain/fundamentals/the-bitcoin-blockchain/README.md
  blockchain/fundamentals/the-bitcoin-blockchain/bitcoin.md
  blockchain/fundamentals/the-bitcoin-blockchain/the-bitcoin-block.md
  blockchain/fundamentals/the-bitcoin-blockchain/the-bitcoin-blockchain.md
Labels: review

#587 Blockchain w4 - Mining
  blockchain/fundamentals/mining/energy-consumption-and-ecology.md
  blockchain/fundamentals/mining/how-can-one-mine.md
  blockchain/fundamentals/mining/mining-pools.md
  blockchain/fundamentals/mining/mining.md
Labels: review

#623 Blockchain c1w5 - Identity and Wallet
  blockchain/fundamentals/wallets/README.md
  blockchain/fundamentals/wallets/bc-practice-identity.md
  blockchain/fundamentals/wallets/bc-practice-signing.md
  blockchain/fundamentals/wallets/identity.md
  blockchain/fundamentals/wallets/wallets.md
Labels: review

#664 Rerender sql
  sql/ddl/alter/add-column.md
  sql/ddl/alter/add-constraint.md
  sql/ddl/alter/add-default-value.md
  sql/ddl/alter/add-rule.md
  sql/ddl/alter/add-trigger.md
  sql/ddl/create/create-a-database.md
  sql/ddl/create/create-a-table.md
  sql/ddl/data-types/add-support-for-other-character-sets.md
  sql/ddl/data-types/encoding-and-collation.md
  sql/ddl/data-types/sql-numeric-data-types.md
  sql/ddl/data-types/sql-string-data-types.md
  sql/ddl/data-types/sql-text-data-type.md
  sql/ddl/indices/create-indexes.md
  sql/ddl/indices/when-to-add-indexes.md
  sql/ddl/storing-blobs/blobs-in-a-rdbms.md
  sql/ddl/storing-blobs/storing-blobs-in-mssql.md
  sql/ddl/storing-blobs/storing-blobs-in-mysql.md
  sql/ddl/storing-blobs/storing-blobs-in-psql.md
  sql/ddl/storing-json/storing-json-in-an-rdbms.md
  sql/ddl/storing-json/storing-json-in-mssql.md
  sql/ddl/storing-json/storing-json-in-mysql.md
  sql/ddl/storing-json/storing-json-in-postgresql.md
  sql/dql/aggregate-queries/avg-clause.md
  sql/dql/aggregate-queries/count-clause.md
  sql/dql/aggregate-queries/distinct-clause.md
  sql/dql/aggregate-queries/group-by-clause.md
  sql/dql/aggregate-queries/min-and-max-clauses.md
  sql/dql/aggregate-queries/sum-clause.md
  sql/dql/basic-queries/order-by-clause.md
  sql/dql/basic-queries/select.md
  sql/dql/basic-queries/where-2.md
  sql/dql/basic-queries/where-3.md
  sql/dql/basic-queries/where.md
  sql/dql/database-clients/command-line-client.md
  sql/dql/database-clients/gui-client.md
  sql/dql/database-clients/java-database-packages.md
  sql/dql/database-clients/node-database-packages.md
  sql/dql/database-clients/python-database-packages.md
  sql/dql/database-clients/what-is-a-database-client.md
  sql/dql/joins/full-join.md
  sql/dql/joins/inner-join.md
  sql/dql/joins/left-and-right-joins.md
  sql/dql/joins/multiple-joins.md
  sql/dql/joins/union.md
  sql/dql/what-is-sql/connection-strings.md
  sql/dql/what-is-sql/database-server-types.md
  sql/dql/what-is-sql/what-is-a-database-server.md
  sql/dql/what-is-sql/what-is-an-rdbms.md
  sql/dql/what-is-sql/what-is-sql.md
  sql/dql/write/delete-clause.md
  sql/dql/write/insert.md
  sql/dql/write/update-clause.md
Labels: review

#666 Added math.random Promise quiz
  javascript/ecmascript-2015/promises/chaining-promises.md
Labels: review

#668 Archive deprecated game wrappers
  .archived/comp-sci/data-structures-and-algorithms/networking-quiz-game/README.md
  .archived/comp-sci/data-structures-and-algorithms/what-should-it-be-stored-in-game/README.md
  .archived/git/core/git-erminology-game/README.md
  .archived/git/core/hooks-arrr-game/README.md
  .archived/ios/dummy-course/README.md
  .archived/java/fundamentals/guess-the-class-game/README.md
  .archived/javascript/ecmascript-2015/destructuring-assignments-game/README.md
  .archived/javascript/ecmascript-2015/ecmascript-time-travel-game/README.md
  .archived/javascript/ecmascript-2015/generators-and-promises-game/README.md
  .archived/javascript/ecmascript-2015/iterators-for-of-spreads-game/README.md
  .archived/javascript/ecmascript-2015/javascript-hard-mode-game/README.md
  .archived/javascript/ecmascript-2015/javascript-hard-mode-ii-game/README.md
  .archived/javascript/ecmascript-2015/map-set-weakmap-weakset-game/README.md
  .archived/javascript/ecmascript-2015/stringing-it-all-together-game/README.md
  .archived/linux/permissions-users/know-your-rights-game/README.md
  .archived/linux/terminals-shells/gotta-know-them-all-game/README.md
  git/essentials/dummy-workout/hooks-arrr.md
  java/fundamentals/dummy-workout/guess-the-class.md
  javascript/ecmascript-2015/dummy-workout/javascript-hard-mode.md
Labels: review

#669 fix broken md sql question
  sql/ddl/create/create-a-table.md
Labels: review

#671 rephrased question to make more sense
  sql/ddl/storing-blobs/blobs-in-a-rdbms.md
Labels: review

#673 Update database-server-types.md
  sql/dql/what-is-sql/database-server-types.md
Labels: review

#674 add example to first question and a standard
  sql/dql/what-is-sql/what-is-sql.md
Labels: review
