Repository enkidevs/curriculum, pull requests merged in 2018-04, with the labels that each got.

#545 [WIP] Update Content to Ampersand.md, Greater-And-Less-Than.md and Non-Brea…
  Web/HTML/best-practices/close-all-html-elements.md
  Web/HTML/best-practices/doctype-always-first.md
  Web/HTML/html-entities/ampersand.md
  Web/HTML/html-entities/copyright.md
  Web/HTML/html-entities/greater-and-less-than.md
  Web/HTML/html-entities/non-breaking-space.md
Labels: review

#677 Reorder sql
  sql/dql/README.md
  sql/dql/basic-queries/README.md
  sql/dql/basic-selects/README.md
  sql/dql/basic-selects/sql-practice-select-1.md
  sql/dql/basic-selects/sql-practice-select-2.md
  sql/dql/basic-selects/sql-practice-where-comparison.md
  sql/dql/database-clients/README.md
  sql/dql/database-clients/connection-strings.md
  sql/dql/what-is-sql/README.md
  sql/dql/what-is-sql/database-server-types.md
  sql/dql/what-is-sql/what-is-a-database-client.md
  sql/dql/what-is-sql/what-is-a-database-server.md
  sql/dql/what-is-sql/what-is-an-rdbms.md
Labels: review

#678 rewording and formatting tests
  sql/dql/basic-selects/sql-practice-select-1.md
  sql/dql/joins/README.md
  sql/dql/joins/sql-practice-average-aggregate-multiple-tables.md
  sql/dql/joins/sql-practice-join-multiple-tables.md
  sql/dql/what-is-sql/sql-practice-what-is-sql.md
Labels: review

#681 patch sudo-fu, set as game
  linux/user-and-file-management/file-permissions/README.md
Labels: review

#682 patch remove from workout archived insight
  python/core/functions/README.md
Labels: review

#683 Sql tweaks
  sql/ddl/alter/add-constraint.md
  sql/dql/basic-selects/sql-practice-select-1.md
  sql/dql/joins/union.md
  sql/dql/what-is-sql/database-server-types.md
  sql/dql/what-is-sql/sql-practice-what-is-sql.md
  sql/dql/what-is-sql/what-is-a-database-client.md
  sql/dql/what-is-sql/what-is-a-database-server.md
  sql/dql/what-is-sql/what-is-an-rdbms.md
  sql/dql/what-is-sql/what-is-sql.md
Labels: review

#688 Os merge
  comp-sci/networking/tools/network-statistics-tools.md
  linux/jobs-and-processes-data-manipulation/basics-process-management/the-process-tree.md
  linux/jobs-and-processes-data-manipulation/grep-and-background-tasks/how-to-pause-a-process-and-run-others-in-the-background.md
  python/core/basic-file-manipulation/i-o-functions.md
  python/core/fundamental-data-structures-ii/built-in-list-methods.md
  sql/ddl/indices/create-indexes.md
  sql/dql/database-clients/command-line-client.md
  sql/dql/database-clients/gui-client.md
  web/html-and-css-basics/practical-css/c-s-splat.md
Labels: review

#690 That backtick shouldn't be there!
  sql/dql/joins/union.md
Labels: review

#693 Fix revision question answer
  sql/dql/aggregate-queries/count-clause.md
Labels: SQL, bug, review

#694 Changing general markdown bold syntax to slack bold syntax
  sql/ddl/create/sql-practice-create-table.md
  sql/ddl/create/sql-practice-define-relationships-2.md
  sql/ddl/create/sql-practice-define-relationships-3.md
  sql/ddl/create/sql-practice-define-relationships-4.md
  sql/ddl/create/sql-practice-define-relationships.md
  sql/ddl/data-types/sql-numeric-data-types.md
  sql/ddl/indices/sql-practice-define-indexes.md
  sql/dql/basic-queries/sql-practice-select.md
  sql/dql/basic-selects/sql-practice-select-2.md
  sql/dql/basic-selects/sql-practice-where-comparison.md
Labels: review

#695 Misc changes to SQL
  sql/ddl/alter/add-column.md
  sql/ddl/alter/add-constraint.md
  sql/ddl/alter/add-default-value.md
  sql/ddl/alter/add-trigger.md
  sql/ddl/alter/sql-practice-alter-table-2.md
  sql/ddl/alter/sql-practice-define-default-seq-2.md
  sql/ddl/alter/sql-practice-define-default-seq-3.md
  sql/ddl/alter/sql-practice-define-default-seq-4.md
  sql/ddl/alter/sql-practice-define-default-seq.md
  sql/ddl/create/create-a-table.md
  sql/ddl/create/sql-practice-create-table-2.md
  sql/ddl/create/sql-practice-create-table-3.md
  sql/ddl/create/sql-practice-create-table-4.md
  sql/ddl/create/sql-practice-create-table.md
  sql/ddl/create/sql-practice-define-relationships-2.md
  sql/ddl/create/sql-practice-define-relationships-3.md
  sql/ddl/create/sql-practice-define-relationships-4.md
  sql/ddl/create/sql-practice-define-relationships.md
  sql/ddl/indices/sql-practice-define-indexes.md
  sql/ddl/indices/sql-practice-sql-indexes2.md
  sql/dql/aggregate-queries/sql-practice-aggregate-average.md
  sql/dql/aggregate-queries/sql-practice-aggregate-group.md
  sql/dql/aggregate-queries/sql-practice-aggregate-single-table-2.md
  sql/dql/aggregate-queries/sql-practice-aggregate-single-table.md
  sql/dql/aggregate-queries/sql-practice-aggregate-table-max-filter.md
  sql/dql/aggregate-queries/sql-practice-aggregate-table-min-and-max.md
  sql/dql/aggregate-queries/sum-clause.md
  sql/dql/basic-queries/order-by-clause.md
  sql/dql/basic-queries/select.md
  sql/dql/basic-queries/sql-practice-order-results.md
  sql/dql/basic-queries/sql-practice-select.md
  sql/dql/basic-queries/sql-practice-string-matching.md
  sql/dql/basic-queries/where-3.md
  sql/dql/basic-queries/where.md
  sql/dql/basic-selects/select-where.md
  sql/dql/basic-selects/sql-practice-select-1.md
  sql/dql/basic-selects/sql-practice-select-2.md
  sql/dql/basic-selects/sql-practice-where-comparison.md
  sql/dql/database-clients/java-database-packages.md
  sql/dql/database-clients/node-database-packages.md
  sql/dql/database-clients/python-database-packages.md
  sql/dql/joins/full-join.md
  sql/dql/joins/inner-join.md
  sql/dql/joins/left-and-right-joins.md
  sql/dql/joins/multiple-joins.md
  sql/dql/joins/sql-practice-average-aggregate-multiple-tables.md
  sql/dql/joins/sql-practice-join-multiple-tables.md
  sql/dql/joins/sql-practice-max-aggregate-multiple-tables.md
  sql/dql/joins/sql-practice-min-max-multiple-tables.md
  sql/dql/joins/union.md
  sql/dql/what-is-sql/what-is-an-rdbms.md
  sql/dql/what-is-sql/what-is-sql.md
  sql/dql/write/delete-clause.md
  sql/dql/write/insert.md
  sql/dql/write/sql-practice-delete.md
  sql/dql/write/update-clause.md
Labels: review

#697 [Fix] Button is at the bottom of dialogues, not the top
  sql/dql/basic-selects/sql-practice-select-2.md
  sql/dql/basic-selects/sql-practice-where-comparison.md
Labels: review

#698 Sql copy fix
  sql/ddl/alter/sql-practice-alter-table.md
  sql/dql/basic-queries/sql-practice-select.md
  sql/dql/what-is-sql/sql-practice-what-is-sql.md
Labels: review

#700 Bolding actionable items
  sql/ddl/alter/sql-practice-alter-table.md
  sql/ddl/alter/sql-practice-define-default-seq-2.md
  sql/ddl/alter/sql-practice-define-default-seq-4.md
  sql/ddl/alter/sql-practice-define-default-seq.md
  sql/ddl/create/sql-practice-create-table-2.md
  sql/ddl/create/sql-practice-create-table-3.md
  sql/ddl/create/sql-practice-create-table-4.md
  sql/ddl/create/sql-practice-create-table.md
  sql/ddl/create/sql-practice-define-relationships.md
  sql/dql/basic-queries/sql-practice-order-results.md
  sql/dql/basic-queries/sql-practice-select.md
  sql/dql/basic-selects/sql-practice-select-1.md
  sql/dql/basic-selects/sql-practice-select-2.md
  sql/dql/basic-selects/sql-practice-where-comparison.md
  sql/dql/what-is-sql/sql-practice-what-is-sql.md
Labels: review

#709 Trigger progression changes
  javascript/browser-apis/README.md
Labels: review

#546 Rewrite and fix python insights
  python/core/advanced-queues/prioritize-your-queue.md
  python/core/advanced-queues/queue-s-and-threads.md
  python/core/advanced-queues/special-queue-methods.md
  python/core/basic-file-manipulation/how-to-open-a-file-object.md
  python/core/basic-file-manipulation/other-operations-on-files.md
  python/core/bits-bytes-hexadecimals/bytes-type.md
  python/core/console-and-operators/execution-order-of-arithmetic-operators.md
  python/core/console-and-operators/indentation-and-commenting.md
  python/core/console-and-operators/printing-to-the-console.md
  python/core/fundamental-data-structures-ii/del-statement-for-lists.md
  python/core/fundamental-data-structures/dictionary-standard-mapping-type.md
  python/core/fundamental-data-structures/variables-and-types.md
  python/core/math-recipes/math-for-complex-numbers.md
  python/core/meet-python/python-2.md
  python/core/meet-python/python-hello-world.md
  python/core/meet-python/what-is-python.md
  python/core/meet-python/why-learn-python.md
  python/core/more-on-dictionaries/dictionary-view-objects.md
  python/core/more-on-lists/using-a-list-as-a-stack.md
  python/core/recipes/parallel-sorting-of-lists.md
  python/core/string-recipes/format-text-paragraphs-with-textwrap.md
  python/core/string-recipes/stringprep-module.md
  python/functional-programming/iterators/the-itertools-module.md
Labels: Computer Science, Python, good first issue, review

#719 Js standards coverage
  javascript/core/array-methods/apply-map-function-to-array-items.md
  javascript/core/array-methods/filtering-items-out-of-an-array.md
  javascript/core/array-methods/get-a-random-item-from-an-array.md
  javascript/core/array-methods/how-to-merge-two-arrays.md
  javascript/core/array-methods/js-practice-array-concat.md
  javascript/core/array-methods/js-practice-array-every.md
  javascript/core/array-methods/js-practice-array-filter.md
  javascript/core/array-methods/js-practice-array-map.md
  javascript/core/array-methods/js-practice-array-reduce.md
  javascript/core/array-methods/js-practice-array-reverse.md
  javascript/core/array-methods/shuffle-an-array-using-sort-and-random.md
  javascript/core/arrays/arrays-can-be-used-as-stack.md
  javascript/core/arrays/arrays.md
  javascript/core/arrays/js-practice-array-isarray.md
  javascript/core/arrays/js-practice-array-push.md
  javascript/core/arrays/js-practice-array-splice.md
  javascript/core/arrays/js-practice-arrays.md
  javascript/core/arrays/setting-the-length-of-an-array.md
  javascript/core/arrays/splice.md
  javascript/core/flow-control/if-statement.md
  javascript/core/flow-control/js-practice-for-loops.md
  javascript/core/flow-control/loops-part-1.md
  javascript/core/flow-control/loops-part-2.md
  javascript/core/functions-ii/setting-default-values-with-short-circuiting.md
  javascript/core/objects/deleting-properties.md
  javascript/core/objects/hasownproperty-method.md
  javascript/core/objects/js-practice-objects.md
  javascript/core/objects/keywords-in-hash-keys.md
  javascript/core/objects/object-part-1.md
  javascript/core/objects/object-part-2.md
  javascript/core/types-ii/truthy-falsy-gotchas.md
  javascript/core/types-ii/truthy-falsy.md
  javascript/core/types-ii/weak-vs-strict-equality-operator.md
  javascript/core/types-ii/you-can-t-handle-the-truth.md
  javascript/core/types/js-practice-booleans.md
  javascript/node/patterns/process-nexttick-callback-pattern.md
Labels: review

#720 not good links on this one
  sql/dql/what-is-sql/sql-practice-what-is-sql.md
Labels: review

#625 Blockchain c1w6 - Anonimity
  blockchain/fundamentals/anonimity/anonymity.md
  blockchain/fundamentals/anonimity/how-to-de-anonymize-bitcoin.md
  blockchain/fundamentals/anonimity/mixing.md
Labels: review

#704 [Python PQ/RQ] Control Structures
  python/core/console-and-operators/arithmetic-operators.md
  python/core/control-structures/chain-comparison-operators.md
  python/core/control-structures/the-in-operator.md
  python/core/control-structures/the-not-operator.md
Labels: Python, review

#706 [Python PQ/RQ] Looping
  python/core/looping/nested-loops.md
  python/core/looping/using-else-in-loops.md
  python/core/looping/while-loops.md
Labels: Python, review

#707 [Python PQ/RQ] Looping
  python/core/functions/calling-functions.md
  python/core/functions/the-return-statement.md
Labels: Python, review

#708 [Python PQ/RQ] Strings and Datetime Module
  python/core/playing-with-time/datetime-object.md
  python/core/working-with-strings/efficient-concatenation-with-join.md
Labels: Python, review

#713 [Python PQ/RQ] Classes
  python/core/classes-i/class-keywords.md
  python/core/classes-i/using-classes.md
  python/core/classes-ii/method-objects.md
  python/core/classes-iii/metaclasses.md
Labels: Python, review

#705 [Python PQ/RQ] Fundamental Data Structures
  python/core/fundamental-data-structures-ii/built-in-list-methods.md
  python/core/fundamental-data-structures-ii/del-statement-for-lists.md
  python/core/fundamental-data-structures/dictionary-standard-mapping-type.md
Labels: Python, review

#722 [Python PQ/RQ] Recipies and Sets
  python/core/more-on-lists/using-a-list-as-a-stack.md
  python/core/more-on-sets/complex-set-operations.md
  python/core/more-on-sets/immutable-sets-with-frozenset.md
  python/core/recipes/combining-multiple-lists-item-by-item.md
  python/core/string-recipes/stringprep-module.md
Labels: Python, review

#729 Patch bugging code
  python/core/dummy-workout/bugging-code.md
Labels: review

#732 added highlight that maybe makes this easier
  sql/dql/basic-queries/order-by-clause.md
Labels: review

#725 [Python PQ/RQ] Tips
  python/core/tips/dynamic-typing.md
  python/core/tips/exiting-the-interpreter.md
  python/core/tips/following-pep-8-styling-guideline.md
  python/core/tips/pretty-print-data-structures.md
Labels: Python, review

#726 [Python PQ/RQ] Memory
  python/core/memory-allocation/memory-leaks.md
  python/core/memory-allocation/python-garbage-collector.md
Labels: Python, review

#727 [Python PQ/RQ] Comprehension
  python/functional-programming/comprehension/list-comprehension.md
  python/functional-programming/comprehension/nested-lists-comprehension.md
  python/functional-programming/comprehension/set-comprehension.md
  python/functional-programming/comprehension/speed-up-your-for-loop-using-map-or-list-comprehensions.md
Labels: review

#489 Add 5 new Python quizzes
  python/core/classes-i/python-inheritance.md
  python/core/classes-ii/private-variables.md
  python/core/control-structures/chain-comparison-operators.md
  python/core/functions/nested-functions.md
  python/core/is-your-python-healthy/exception-handling.md
Labels: review

#738 remove workout tag from first core section
  javascript/core/arrays/arrays-can-be-used-as-stack.md
  javascript/core/arrays/arrays.md
  javascript/core/arrays/setting-the-length-of-an-array.md
  javascript/core/arrays/splice.md
  javascript/core/flow-control/data-type-comparison-in-switch-statements.md
  javascript/core/flow-control/if-statement.md
  javascript/core/flow-control/loops-part-1.md
  javascript/core/flow-control/loops-part-2.md
  javascript/core/functions-i/access-a-function-s-arguments-as-an-array.md
  javascript/core/functions-i/declaring-functions.md
  javascript/core/functions-i/function-arguments.md
  javascript/core/functions-i/function-constructor-vs-function-expression.md
  javascript/core/functions-i/functions-can-be-declared-after-use.md
  javascript/core/intro-js/console-in-javascript.md
  javascript/core/intro-js/javascript-history.md
  javascript/core/intro-js/javascript-or-ecmascript.md
  javascript/core/intro-js/using-javascript-on-a-web-page.md
  javascript/core/objects/deleting-properties.md
  javascript/core/objects/hasownproperty-method.md
  javascript/core/objects/keywords-in-hash-keys.md
  javascript/core/objects/object-part-1.md
  javascript/core/objects/object-part-2.md
  javascript/core/syntax/double-and-single-quotes.md
  javascript/core/syntax/javascript-basics-part-1.md
  javascript/core/syntax/javascript-basics-part-2.md
  javascript/core/syntax/strict-mode.md
  javascript/core/types-ii/the-difference-between-null-undefined-and-nan.md
  javascript/core/types-ii/truthy-falsy-gotchas.md
  javascript/core/types-ii/truthy-falsy.md
  javascript/core/types-ii/weak-vs-strict-equality-operator.md
  javascript/core/types/be-careful-when-using-typeof.md
  javascript/core/types/types-boolean-and-number.md
  javascript/core/types/types-hoisting.md
  javascript/core/types/types-introduction.md
  javascript/core/types/types-string.md
  javascript/core/types/types-undefined-and-null.md
  javascript/npm/intro-npm/semantic-versioning.md
Labels: review
