Repository enkidevs/curriculum, pull requests merged in 2019-04, with the labels that each got.

#1281 Update:curriculum/git/essentials/fundamentals/how-does-git-work.md
  git/essentials/fundamentals/how-does-git-work.md
Labels: awaiting review

#1282 Update curriculum/python/core/control-structures/boolean-operators.md
  python/core/control-structures/boolean-operators.md
Labels: awaiting review, review

#1289 Update: curriculum/python/core/control-structures/indentation-and-commenting.md
  python/core/control-structures/indentation-and-commenting.md
Labels: awaiting review, review

#1285 Update: curriculum/python/core/console-and-operators/more-complex-arithmetic-operators.md
  python/core/console-and-operators/more-complex-arithmetic-operators.md
Labels: awaiting review, review

#1287 Update: javascript/core/types/weak-vs-strict-equality-operator
  javascript/core/types/weak-vs-strict-equality-operator.md
Labels: awaiting review, review

#1283 Update: curriculum/javascript/core/dummy-workout/if-else-shortcut-conditional-operator.md
  javascript/core/dummy-workout/if-else-shortcut-conditional-operator.md
Labels: awaiting review, review

#1292 Improve SQL course names
  sql/ddl/README.md
  sql/dql/README.md
Labels: review

#1295 Update automated-tools.md
  security/appsec/intro/automated-tools.md
Labels: review

#1299 Update javascript / ecmascript-2015 / function-improvements /arrow-functions-part-1.md
  javascript/ecmascript-2015/function-improvements/arrow-functions-part-1.md
Labels: review

#1297 Update javascript / ecmascript-2015 / array-updates / array-copywithin.md
  javascript/ecmascript-2015/array-updates/array-copywithin.md
Labels: review

#1304 Update / javascript / core / errors /online-debugging-options.md
  javascript/core/errors/online-debugging-options.md
Labels: review

#1303 Update / javascript / core / js-history /javascript-or-ecmascript.md
  javascript/core/js-history/javascript-or-ecmascript.md
Labels: review

#1302 Update javascript / core / array-methods /apply-map-function-to-array-items.md
  javascript/core/array-methods/apply-map-function-to-array-items.md
Labels: review

#1301 Update/ javascript / core / async / csp-using-js-csp.md
  javascript/core/async/csp-using-js-csp.md
Labels: review

#1296 Update what-else-do-you-need-to-know.md
  security/appsec/intro/what-else-do-you-need-to-know.md
Labels: review

#1294 Update owasp.md
  security/appsec/intro/owasp.md
Labels: review

#1293 Update what-is-appsec.md
  security/appsec/intro/what-is-appsec.md
Labels: review

#1290 Update proxy-interception-points.md
  javascript/ecmascript-2015/generators-proxy/proxy-interception-points.md
Labels: review

#1284 Update: curriculum/python/core/more-on-lists/using-a-list-as-a-stack.md
  python/core/more-on-lists/using-a-list-as-a-stack.md
Labels: awaiting review, review

#1305 Update a-great-font-resource-google-font-api.md
  web/styling/typography/a-great-font-resource-google-font-api.md
Labels: review

#1307 (Web) WSA-satisfaction updates
  web/styling/centring-recipes/vertically-center-anything.md
Labels: review

#1306 (SQL) WSA-satisfaction updates
  sql/ddl/data-types/encoding-and-collation.md
Labels: review

#1309 Update what-is-sql.md
  sql/dql/what-is-sql/what-is-sql.md
Labels: review
