Repository enkidevs/curriculum, pull requests merged in 2019-02, with the labels that each got.

#1193 [part 7] Add aspects to Git
  git/essentials/features-i/check-the-reflog.md
  git/essentials/features-i/get-the-most-out-of-git.md
  git/essentials/features-i/git-ignore.md
  git/essentials/features-i/reset-vs-revert.md
  git/essentials/features-i/subdirectory-checkout.md
Labels: awaiting review, review

#1195 [part 9] Add aspects to Git
  git/essentials/features-iii/create-a-global-git-commit-hook.md
  git/essentials/features-iii/pushing-tags-to-a-server.md
  git/essentials/features-iii/revision-tools.md
  git/essentials/features-iii/useful-commit-hooks.md
  git/essentials/features-iii/using-tags-for-version-control.md
  git/essentials/features-iii/what-is-a-hook.md
Labels: awaiting review, review

#1192 [part 6] Add aspects to Git
  git/essentials/branching/fetching-a-remote-branch.md
  git/essentials/branching/managing-branches.md
  git/essentials/branching/pulling-a-remote-branch.md
  git/essentials/branching/pushing-to-a-remote-branch.md
  git/essentials/branching/setting-the-upstream-branch.md
  git/essentials/branching/what-is-rebasing.md
Labels: awaiting review, review

#1216 Add aspects to curriculum/git/workflow/workflow
  git/workflow/workflow/general-github-workflow.md
  git/workflow/workflow/git-hub.md
  git/workflow/workflow/squashing-commits.md
  git/workflow/workflow/workflow-long-running-branches.md
  git/workflow/workflow/workflow-topic-branches.md
Labels: awaiting review, review

#1217 Add aspects to curriculum/git/workflow/merges/
  git/workflow/merges/merging-under-the-hood.md
  git/workflow/merges/rebasing.md
  git/workflow/merges/remember-the-results-of-previous-hunk-conflicts.md
  git/workflow/merges/solving-basic-merge-conflicts.md
  git/workflow/merges/the-golden-rule-of-rebasing.md
Labels: awaiting review, review

#1218 Add aspects to curriculum/git/workflow/help/
  git/workflow/help/getting-help.md
  git/workflow/help/how-to-unstage-a-staged-file.md
  git/workflow/help/modifying-a-previous-commit.md
  git/workflow/help/recover-lost-code.md
  git/workflow/help/undo-a-committed-snapshot.md
Labels: awaiting review, review

#1219 Add aspects to curriculum/git/workflow/finding-commits/
  git/workflow/finding-commits/locate-a-commit-by-its-hash.md
  git/workflow/finding-commits/search-by-commit-message-keyword.md
  git/workflow/finding-commits/search-for-commits-by-author.md
  git/workflow/finding-commits/specify-a-commit-by-its-ancestry.md
  git/workflow/finding-commits/specify-a-range-of-commits-using-double-dot-syntax.md
Labels: awaiting review, review

#1220 Add aspects to curriculum/git/workflow/logging/
  git/workflow/logging/limiting-log-output-by-time.md
  git/workflow/logging/logging.md
  git/workflow/logging/make-your-log-output-pretty.md
  git/workflow/logging/show-history-of-a-function.md
  git/workflow/logging/view-your-commit-history-in-a-graph.md
Labels: awaiting review, review

#1222 Add aspects to curriculum/git/workflow/staging-i/
  git/workflow/staging-i/intent-to-add.md
  git/workflow/staging-i/interactive-staging.md
  git/workflow/staging-i/interactively-stage-patches.md
  git/workflow/staging-i/interactively-unstage-changes.md
  git/workflow/staging-i/use-short-status-to-make-output-more-compact.md
Labels: awaiting review, review

#1223 Add aspects to curriculum/git/workflow/staging-ii/
  git/workflow/staging-ii/create-a-new-branch-from-a-stash.md
  git/workflow/staging-ii/delete-all-untracked-files.md
  git/workflow/staging-ii/stashing-changes.md
  git/workflow/staging-ii/untrack-a-directory-file-without-deleting-it.md
  git/workflow/staging-ii/useful-stashing-options.md
Labels: awaiting review, review

#1224 Add aspects to curriculum/git/workflow/tips/
  git/workflow/tips/avoiding-whitespace-issues.md
  git/workflow/tips/cache-your-authentication-details-to-save-time.md
  git/workflow/tips/custom-colour-options.md
  git/workflow/tips/overcome-line-ending-issues.md
  git/workflow/tips/sign-your-work-using-gpg.md
Labels: awaiting review, review

#1225 Add aspects to curriculum/git/workflow/work-smart/
  git/workflow/work-smart/add-autocorrect-to-git.md
  git/workflow/work-smart/tracking-shorthands.md
  git/workflow/work-smart/upstream-tracking-shorthand.md
  git/workflow/work-smart/using-aliases-for-git-commands.md
  git/workflow/work-smart/you-can-use-git-offline.md
Labels: awaiting review, review

#1226 Add aspects to curriculum/git/workflow/branches/
  git/workflow/branches/checkout-the-previous-branch.md
  git/workflow/branches/master-and-origin-aren-t-special.md
  git/workflow/branches/move-the-last-commit-to-a-new-branch.md
  git/workflow/branches/prune-remote-tracking-references.md
  git/workflow/branches/viewing-your-tracking-branches.md
Labels: awaiting review, review

#1227 Add aspects to curriculum/git/essentials/dummy-workout/
  git/essentials/dummy-workout/adding-a-remote-repository.md
  git/essentials/dummy-workout/fetching-and-pulling.md
  git/essentials/dummy-workout/finding-a-tag.md
  git/essentials/dummy-workout/hooks-arrr.md
  git/essentials/dummy-workout/how-to-change-your-most-recent-commit.md
  git/essentials/dummy-workout/how-to-set-your-username-and-email.md
  git/essentials/dummy-workout/how-to-unmodify-a-modified-file.md
  git/essentials/dummy-workout/ignore-files-in-git.md
  git/essentials/dummy-workout/on-off.md
  git/essentials/dummy-workout/perform-a-dry-run.md
  git/essentials/dummy-workout/remote-repositories-fetching-and-pushing.md
  git/essentials/dummy-workout/remote-repositories-viewing-editing-and-deleting.md
  git/essentials/dummy-workout/the-three-states-in-git.md
Labels: awaiting review, review

#1229 Adding aspects to security > data link layer
  security/securing-unix-the-osi-model/data-link-layer/identifying-the-data-link-layer.md
  security/securing-unix-the-osi-model/data-link-layer/securing-the-data-link-layer.md
Labels: review

#1230 Adding aspects to security > application layer
  security/securing-unix-the-osi-model/application-layer/identifying-the-application-layer.md
  security/securing-unix-the-osi-model/application-layer/securing-the-application-layer.md
Labels: review

#1182 Add aspects to user and file management course
  linux/user-and-file-management/bash-environment/adding-directories-to-your-path.md
  linux/user-and-file-management/bash-environment/customizing-bash-via-bashrc.md
  linux/user-and-file-management/bash-environment/manipulating-environment-variables.md
  linux/user-and-file-management/bash-environment/understanding-the-path-environment-variable.md
  linux/user-and-file-management/bash-environment/what-are-environment-variables.md
  linux/user-and-file-management/conditions/compound-commands.md
  linux/user-and-file-management/conditions/conditional-command-execution-operator.md
  linux/user-and-file-management/conditions/else-statements-using-the-operator.md
  linux/user-and-file-management/conditions/sequential-execution-using-the-statement-separator.md
  linux/user-and-file-management/conditions/the-test-built-in.md
  linux/user-and-file-management/default-permissions/making-a-file-unalterable-with-chattr.md
  linux/user-and-file-management/default-permissions/the-setgid-permission.md
  linux/user-and-file-management/default-permissions/the-setuid-permission.md
  linux/user-and-file-management/default-permissions/the-sticky-bit-permission.md
  linux/user-and-file-management/default-permissions/understanding-umask.md
  linux/user-and-file-management/file-management-tips-ii/easy-way-of-sharing-files.md
  linux/user-and-file-management/file-management-tips-ii/finding-file-with-regexes.md
  linux/user-and-file-management/file-management-tips-ii/identify-files-using-the-file-command.md
  linux/user-and-file-management/file-management-tips-ii/preserving-permissions-and-structure-with-rsync.md
  linux/user-and-file-management/file-management-tips-ii/working-with-gz-files.md
  linux/user-and-file-management/file-permissions/set-file-permissions-for-users.md
  linux/user-and-file-management/file-permissions/sudo-fu.md
  linux/user-and-file-management/pipeline-tools/progress-of-data-through-a-pipe-with-pv.md
  linux/user-and-file-management/pipeline-tools/shebang-explained.md
  linux/user-and-file-management/pipeline-tools/the-2-1-redirection.md
  linux/user-and-file-management/pipeline-tools/using-xargs-to-build-commands.md
  linux/user-and-file-management/pipelines/difference-between-redirection-and-pipe.md
  linux/user-and-file-management/shell/quick-cd-tips.md
  linux/user-and-file-management/shell/rapidly-invoke-an-editor-to-write-a-long-complex-or-tricky-command.md
  linux/user-and-file-management/shell/terminal-based-browser.md
  linux/user-and-file-management/shell/the-basics-of-environment-variables.md
  linux/user-and-file-management/shell/what-is-a-shell.md
  linux/user-and-file-management/terminal-history/bash-history-reverse-search.md
  linux/user-and-file-management/user-management/adding-new-users-with-useradd.md
  linux/user-and-file-management/user-management/changing-user-passwords-with-passwd.md
  linux/user-and-file-management/user-management/linux-user-management.md
  linux/user-and-file-management/user-management/running-a-command-as-another-local-user.md
  linux/user-and-file-management/user-management/usermod-recipes.md
Labels: review, work in progress

#1238 Add aspects to game
  linux/user-and-file-management/super-users-and-root/know-your-rights.md
Labels: review

#1231 Adding aspects to security > osi model
  security/securing-unix-the-osi-model/osi-model/introducing-the-osi-model.md
Labels: review

#1228 Adding aspects to security > network layer
  security/securing-unix-the-osi-model/network-layer/identifying-the-network-layer.md
  security/securing-unix-the-osi-model/network-layer/securing-the-network-layer.md
Labels: review, work in progress

#1232 Adding aspects to security > presentation layer
  security/securing-unix-the-osi-model/presentation-layer/identifying-the-presentation-layer.md
  security/securing-unix-the-osi-model/presentation-layer/securing-the-presentation-layer.md
Labels: review

#1233 Adding aspects to security > physical layer
  security/securing-unix-the-osi-model/physical-layer/identifying-the-physical-layer.md
  security/securing-unix-the-osi-model/physical-layer/securing-the-physical-layer.md
Labels: review

#1234 Adding aspects to security > session layer
  security/securing-unix-the-osi-model/session-layer/identifying-the-session-layer.md
  security/securing-unix-the-osi-model/session-layer/securing-the-session-layer.md
Labels: review

#1235 Adding aspects to security > transport layer
  security/securing-unix-the-osi-model/transport-layer/identifying-the-transport-layer.md
  security/securing-unix-the-osi-model/transport-layer/securing-the-transport-layer.md
Labels: review

#1237 Add JavaScript Node aspects
  javascript/node/best-practices/process-env-performance.md
  javascript/node/express-ii/cookie-session-in-express.md
  javascript/node/express-ii/gzip-compression-for-express.md
  javascript/node/express-ii/log-with-morgan-in-express.md
  javascript/node/express-ii/session-handling-in-express.md
  javascript/node/express-ii/vhost-in-express.md
  javascript/node/express/body-parser-in-express.md
  javascript/node/express/easy-way-to-deliver-html-pages-with-express.md
  javascript/node/express/error-handler-in-express.md
  javascript/node/express/response-object-additional-properties-in-express.md
  javascript/node/express/using-express-4-0-router.md
  javascript/node/tools/automatic-compilation-for-node-with-nodemon.md
  javascript/node/web-servers/basic-web-server-with-express.md
  javascript/node/web-servers/http-server-in-node.md
Labels: review

#1239 Fix aspect typo in JHat insight
  java/data-management/tools-i/the-jhat-tool.md
Labels: review

#1242 Tag remaining ecmascript with aspects
  javascript/ecmascript-2015/destructuring/destructuring-assignments.md
  javascript/ecmascript-2015/generators-proxy/generators-and-promises.md
  javascript/ecmascript-2015/iterators-generators/iterators-for-of-spreads.md
  javascript/ecmascript-2015/master-es6-features/javascript-hard-mode-ii.md
  javascript/ecmascript-2015/promises/js-practice-async-await.md
  javascript/ecmascript-2015/promises/js-practice-promises.md
  javascript/ecmascript-2015/spread-map-set-math/js-practice-spreads.md
  javascript/ecmascript-2015/spread-map-set-math/map-data-structure.md
  javascript/ecmascript-2015/spread-map-set-math/map-set-weakmap-weakset.md
  javascript/ecmascript-2015/string-flexibility/stringing-it-all-together.md
Labels: review

#1249 only rearranges, no archives
  javascript/ecmascript-2015/README.md
  javascript/ecmascript-2015/array-updates/README.md
  javascript/ecmascript-2015/array-updates/array-copywithin.md
  javascript/ecmascript-2015/array-updates/array-extensions.md
  javascript/ecmascript-2015/array-updates/searching-array-methods.md
  javascript/ecmascript-2015/array-updates/typed-arrays.md
  javascript/ecmascript-2015/destructuring/README.md
  javascript/ecmascript-2015/destructuring/argument-destructuring-with-defaults.md
  javascript/ecmascript-2015/destructuring/defaults-values-apply-only-to-undefined-and-not-to-null.md
  javascript/ecmascript-2015/destructuring/destructuring-assignments.md
  javascript/ecmascript-2015/destructuring/destructuring-part-1.md
  javascript/ecmascript-2015/destructuring/destructuring-part-2.md
  javascript/ecmascript-2015/destructuring/destructuring-part-3.md
  javascript/ecmascript-2015/es6-quirks/README.md
  javascript/ecmascript-2015/intro-ecmascript/README.md
  javascript/ecmascript-2015/intro-ecmascript/const-part-1.md
  javascript/ecmascript-2015/intro-ecmascript/const-part-2.md
  javascript/ecmascript-2015/intro-ecmascript/ecmascript.md
  javascript/ecmascript-2015/intro-ecmascript/let-part-1.md
  javascript/ecmascript-2015/intro-ecmascript/let-part-2.md
  javascript/ecmascript-2015/master-es6-features/README.md
  javascript/ecmascript-2015/master-es6-features/es6-dynamic-property-keys-in-mongo-like-set-clauses.md
  javascript/ecmascript-2015/number-extensions/README.md
  javascript/ecmascript-2015/number-extensions/binary-and-octal-notation-in-es6.md
  javascript/ecmascript-2015/number-extensions/math-extensions.md
  javascript/ecmascript-2015/number-extensions/number-extensions-part-1.md
  javascript/ecmascript-2015/number-extensions/number-extensions-part-2.md
  javascript/ecmascript-2015/spread-map-set-math/README.md
  javascript/ecmascript-2015/spread-map-set-math/weakmap-in-es6.md
  javascript/ecmascript-2015/string-number-extensions/README.md
  javascript/ecmascript-2015/string-upgrades/README.md
  javascript/ecmascript-2015/string-upgrades/ecmascript-time-travel.md
  javascript/ecmascript-2015/string-upgrades/internationalization-localization.md
  javascript/ecmascript-2015/string-upgrades/string-extensions.md
  javascript/ecmascript-2015/string-upgrades/template-literals.md
  javascript/ecmascript-2015/string-upgrades/unicode-in-es6.md
Labels: review

#1245 Add missing aspects to curriculum/javascript/core/intro-js
  javascript/core/intro-js/js-practice-console.md
Labels: review

#1246 Add aspects to curriculum/javascript/core/types/
  javascript/core/types/js-practice-glitch-math.md
  javascript/core/types/js-practice-glitch-numbers.md
  javascript/core/types/js-practice-taking-precedence.md
  javascript/core/types/taking-precedence.md
  javascript/core/types/the-difference-between-null-undefined-and-nan.md
  javascript/core/types/types-boolean-and-number.md
  javascript/core/types/types-undefined-and-null.md
  javascript/core/types/weak-vs-strict-equality-operator.md
Labels: review

#1248 Add aspects to curriculum/javascript/core/async
  javascript/core/async/async-a-history.md
  javascript/core/async/csp-using-js-csp.md
  javascript/core/async/flow-control-using-co.md
  javascript/core/async/js-practice-async.md
  javascript/core/async/js-practice-event-loop.md
  javascript/core/async/the-difference-between-parallel-asynchronous-and-concurrent.md
Labels: review

#1247 Add aspects to curriculum/javascript/core/async-tips/
  javascript/core/async-tips/error-first-callbacks.md
  javascript/core/async-tips/name-your-callback-functions-to-avoid-callback-hell.md
  javascript/core/async-tips/transform-values-into-promises.md
  javascript/core/async-tips/using-timers-with-extra-arguments.md
Labels: review

#1250 Add aspects to curriculum/javascript/core/objects/
  javascript/core/objects/converting-to-and-from-json.md
  javascript/core/objects/js-practice-glitch-object-properties.md
  javascript/core/objects/js-practice-glitch-objects.md
  javascript/core/objects/js-practice-objects.md
  javascript/core/objects/keywords-in-hash-keys.md
  javascript/core/objects/object-part-1.md
  javascript/core/objects/object-part-2.md
Labels: review, work in progress

#1251 Add aspects to curriculum/javascript/core/arrays/
  javascript/core/arrays/arrays.md
  javascript/core/arrays/foo-features-and-fun-facts.md
  javascript/core/arrays/js-practice-array-isarray.md
  javascript/core/arrays/js-practice-array-push.md
  javascript/core/arrays/js-practice-array-splice.md
  javascript/core/arrays/js-practice-arrays.md
  javascript/core/arrays/js-practice-glitch-array-access.md
  javascript/core/arrays/js-practice-glitch-array-for-loop.md
  javascript/core/arrays/js-practice-glitch-array.md
  javascript/core/arrays/setting-the-length-of-an-array.md
  javascript/core/arrays/splice.md
Labels: review, work in progress

#1264 Add aspects to curriculum/javascript/core/functions-i
  javascript/core/functions-i/access-a-function-s-arguments-as-an-array.md
  javascript/core/functions-i/function-arguments.md
  javascript/core/functions-i/functions-can-be-declared-after-use.md
  javascript/core/functions-i/js-practice-glitch-functions.md
Labels: review, work in progress

#1253 Add aspects to curriculum/javascript/core/recipes-ii/
  javascript/core/recipes-ii/avoid-using-with.md
  javascript/core/recipes-ii/counting-the-months-from-zero.md
  javascript/core/recipes-ii/js-practice-date.md
  javascript/core/recipes-ii/milliseconds-since-epoch.md
Labels: review, work in progress

#1254 Add aspects to curriculum/javascript/core/recipes-i
  javascript/core/recipes-i/easily-generate-a-random-hex-color.md
  javascript/core/recipes-i/format-currency-in-javascript.md
  javascript/core/recipes-i/js-practice-math-round.md
  javascript/core/recipes-i/js-practice-number-tofixed.md
  javascript/core/recipes-i/js-practice-number-tostring.md
  javascript/core/recipes-i/quick-way-to-format-integers-with-a-fixed-number-of-digits.md
  javascript/core/recipes-i/round-numbers-to-n-decimals.md
  javascript/core/recipes-i/using-the-double-tilde-game.md
  javascript/core/recipes-i/using-the-double-tilde.md
Labels: review, work in progress

#1255 Add aspects to curriculum/javascript/core/functions-iii
  javascript/core/functions-iii/bind.md
  javascript/core/functions-iii/changing-a-functions-context-with-fn-call-object.md
  javascript/core/functions-iii/context-in-javascript.md
  javascript/core/functions-iii/difference-between-call-and-apply-methods.md
  javascript/core/functions-iii/function-call-method.md
Labels: review, work in progress

#1256 Add aspects to curriculum/javascript/core/errors/
  javascript/core/errors/debugging.md
  javascript/core/errors/detect-an-error-type.md
  javascript/core/errors/exceptions.md
  javascript/core/errors/js-practice-custom-errors.md
  javascript/core/errors/js-practice-error-throwing.md
  javascript/core/errors/js-practice-invalid-input.md
Labels: review, work in progress

#1258 Add aspects to curriculum/javascript/core/scope/
  javascript/core/scope/closures.md
  javascript/core/scope/js-practice-closures.md
  javascript/core/scope/js-practice-hoisting.md
  javascript/core/scope/think-you-know-javascript.md
Labels: review, work in progress

#1259 Add aspects to curriculum/javascript/core/functions-ii/
  javascript/core/functions-ii/check-if-a-function-exists.md
  javascript/core/functions-ii/iife-pattern.md
  javascript/core/functions-ii/js-practice-default-parameters.md
  javascript/core/functions-ii/js-practice-this.md
Labels: review, work in progress

#1260 Add aspects to curriculum/javascript/core/strings-ii
  javascript/core/strings-ii/js-practice-string-charat.md
  javascript/core/strings-ii/js-practice-string-concat.md
  javascript/core/strings-ii/js-practice-string-indexof.md
  javascript/core/strings-ii/js-practice-string-slice.md
  javascript/core/strings-ii/js-practice-string-touppercase.md
  javascript/core/strings-ii/js-practice-string-trim.md
  javascript/core/strings-ii/most-efficient-way-to-build-html-strings.md
Labels: review, work in progress

#1262 Add aspects to curriculum/javascript/core/types-ii/
  javascript/core/types-ii/be-careful-when-using-typeof.md
  javascript/core/types-ii/truthy-falsy-gotchas.md
  javascript/core/types-ii/truthy-falsy.md
Labels: review, work in progress

#1263 Add aspects to curriculum/javascript/core/flow-control/
  javascript/core/flow-control/data-type-comparison-in-switch-statements.md
  javascript/core/flow-control/js-practice-for-loops.md
  javascript/core/flow-control/js-practice-glitch-for.md
  javascript/core/flow-control/js-practice-glitch-if.md
  javascript/core/flow-control/js-practice-switch-case.md
  javascript/core/flow-control/js-practice-while-loops.md
  javascript/core/flow-control/loops-part-1.md
  javascript/core/flow-control/loops-part-2.md
Labels: review, work in progress

#1261 Add aspects to curriculum/javascript/core/numbers/
  javascript/core/numbers/base-conversion.md
  javascript/core/numbers/inaccuracy-of-binary-floating-point-format.md
  javascript/core/numbers/infinity-game.md
  javascript/core/numbers/js-practice-math-log.md
  javascript/core/numbers/js-practice-math-max.md
  javascript/core/numbers/js-practice-math-pow.md
  javascript/core/numbers/js-practice-math-random.md
  javascript/core/numbers/js-practice-number-methods-round.md
  javascript/core/numbers/js-practice-number-methods-tostring.md
  javascript/core/numbers/js-practice-number-tostring.md
  javascript/core/numbers/nan-is-a-number.md
  javascript/core/numbers/parsing-numbers-and-ieee-754.md
Labels: review, work in progress

#1266 minor grammar fixes
  javascript/react/intro-react/what-is-react.md
Labels: review

#1267 minor grammar fixes
  javascript/ecmascript-2015/intro-ecmascript/ecmascript-6.md
Labels: review

#1268 Patch broken SVG display in new app for some insights
  comp-sci/data-structures-and-algorithms/intro-graphs/the-graph-data-structure.md
  comp-sci/data-structures-and-algorithms/intro-graphs/the-tree-data-structure.md
  security/securing-unix-the-osi-model/osi-model/introducing-the-osi-model.md
  web/html/citation-elements/intro-cite.md
  web/html/formatting-text-elements/editing-u-mark.md
  web/html/html-entities/greater-and-less-than.md
  web/html/lists/ordered-lists.md
  web/html/lists/unordered-lists.md
  web/styling/flexbox/flexbox-justify-content.md
Labels: review

#1269 Retrigger png generation for some insights
  comp-sci/data-structures-and-algorithms/intro-graphs/the-graph-data-structure.md
  comp-sci/data-structures-and-algorithms/intro-graphs/the-tree-data-structure.md
  security/securing-unix-the-osi-model/osi-model/introducing-the-osi-model.md
  web/html/citation-elements/intro-cite.md
  web/html/formatting-text-elements/editing-u-mark.md
  web/html/html-entities/greater-and-less-than.md
  web/html/lists/ordered-lists.md
  web/html/lists/unordered-lists.md
  web/styling/flexbox/flexbox-justify-content.md
Labels: review
